src/solvespace.cpp

Fix crash when trying to import not .dxf or .dwg files

---

CONTRIBUTING.md
cmake/FindVendoredPackage.cmake
exposed/DOC.txt
exposed/VbDemo.vb
res/locales/en_US.po
res/locales/ru_RU.po
res/locales/uk_UA.po
res/shaders/edge.frag
src/exportvector.cpp
src/graphicswin.cpp
src/group.cpp
src/groupmesh.cpp
src/mesh.cpp
src/platform/cocoamain.mm
src/platform/gtkmain.cpp
src/platform/w32main.cpp
src/polygon.cpp
src/render/gl3shader.cpp
src/textscreens.cpp

A few user-facing. Most are trvial source comment typos. Found using `codespell -q 3 --skip=".po,*.pot"`

Misc. trivial typos

---

res/cocoa/MainMenu.xib
src/platform/guimac.mm

Because of the missing "synthesize acceptsFirstResponder;"
the App crashes immediately on macOS: "unrecognized selector setAcceptsFirstResponder send to SSView".

Fixed macOS build

---

CHANGELOG.md
src/file.cpp

When a sketch that contains no custom styles links a sketch that does contain a custom style, a new custom style is created with the default format. This patch changes that and creates a new style with the same format as in the linked file.

Import styles from linked sketches

---

src/util.cpp

Minor cleanup. As I put in the commit msg:
> Some of these showed up in profiling hotspots. std::abs is
> properly overloaded to not cause undesired conversions, which
> (for numeric values) are often more expensive than you'd expect.
> fabs is not overloaded: it's a C function that only operates on
> doubles.
Confession: when I first started this I thought `fabs` only operated on floats, and thus there were a ton of unnecessary and expensive double->float->double conversions happening. I checked that assumption before making the commit, and thus discovered my misunderstanding. However, this change does not decrease performance, and if nothing else should improve type safety because std::abs is generic (so no matter how the code changes, it won't introduce conversions).
Update: I just …

Replace calls to fabs in util.cpp with calls to std::abs.

---

src/platform/platform.cpp

This is useful for relocatable bundles (e.g., AppImages).
See https://github.com/solvespace/solvespace/issues/347#issuecomment-485226547

Add a lookup for ../share/solvespace

---

src/platform/guigtk.cpp

Ubuntu 18.04 uses GTKMM 3.22.2-2, which doesn't support native file chooser.
Commit bc3e09edbfeb4859218bf51476e34635f45cf249 checks if native file chooser
is available, but the result is overridden with a hardcoded define,
probably for debugging.
Removing the debugging code fixes build on Ubuntu 18.04.

GTK: fix build on Ubuntu 18.04 by removing debug define

---

src/util.cpp

This (as well as some other unexpected locations, like https://github.com/solvespace/solvespace/blob/c6fc0125a21aa27f89ab6e0bb16037f04bc39fd4/src/polygon.cpp#L23 and https://github.com/solvespace/solvespace/blob/c6fc0125a21aa27f89ab6e0bb16037f04bc39fd4/src/util.cpp#L587 ) showed up as a substantial hot-spot when I ran the VS CPU profiler in VS2017 on an x64 build of the latest master, looking at time periods when the GUI was non-responsive and SolveSpace was consuming a full core of CPU "doing something".
This is a fairly small change, but it seemed to improve the profiling results here. I imagine there are further ways to do this, or better ways (do we have profiling data that the early-outs actually improve performance? since this is "inner-loop" code essentially - they might just be …

Small optimization to Vector::Equals to improve performance.

---

src/dsc.h
src/util.cpp

Performance change: moved since they show up disproportionately
in profiling. (or at least, they did in January of 2018. I'm nearly full-time linux now, and I'm strangely better at profiling on Windows, so I didn't re-profile yet.)

Move two members of Vector to be inline.

---

test/CMakeLists.txt
test/harness.cpp

Before, would guess incorrectly if the CMake source tree was specified
via a relative path (since then the path would not start with /).
Now, checks for any backslashes, using them as an indicator that
the backslash is the separator.
Without this, I can't get the test suite to run on Linux, and I'm pretty sure I couldn't get it to run on Windows before.

Fix tests by correcting detection of build path sep.

---

CMakeLists.txt
src/platform/guiwin.cpp

By setting WINVER=0x0501 (Windows XP) in CMakeLists.txt and adding a few
missing defines in guiwin.cpp and configuring OPENGL=1 in CMake
Solvespace (3.0~25b6eba1) compiles and works perfectly on Windows XP.
Tested with MinGW GCC-6.3.0-1
[solvespace_WinXP_3.0_25b6eba1.zip](https://github.com/solvespace/solvespace/files/3210928/solvespace_WinXP_3.0_25b6eba1.zip)

Win32: Restore Windows XP Compatibility

---

src/util.cpp

If an assert triggered in the test suite, it would segfault. This trivially avoids that, letting it do the normal assert things.

Fix CLI/Testsuite crash on assert

---

src/render/render.h

It was griping in shared_ptr code about there being virtual functions without a virtual destructor and creating a non-final class. Easiest way to fix it was to make this a final class.

Fix warning about destructor

---

pkg/snap/.gitignore
pkg/snap/build.sh
pkg/snap/snap/snapcraft.yaml
res/CMakeLists.txt
res/freedesktop/solvespace-snap.desktop

This is a "copy & paste" integration of the solvespace snap repo @ https://github.com/ppd1990/solvespace-snap as discussed in https://github.com/ppd1990/solvespace-snap/issues/2
1. ~~The integration resides in ```$ROOT/snap```. This is what build.snapcraft.io requires. If using the Ubuntu provided build server (and thus easy auto-build on commit) is not wanted, we could move it to mirror the flatpak integration~~
2. ~~The svg icon should probably find its place in ```res/freedesktop``` or we could just use a png icon. At the moment snap packages need an absolute path to an icon.~~
The svg icon was proposed for inclusion in #441 
3. ~~The snap is declared ```grade: stable```. Maybe that should only apply to tagged versions. Some extra logic would be required~~
Publishing of the snap should …

Linux: add support for building snap packages

---

src/group.cpp

Helix should always make a line for the axis.

Make helix origin create a line even if it's in a different group.

---

src/platform/guimac.mm
src/solvespace.cpp

These are the auto-fixable fixes that Xcode could do on macOS Catalina (Xcode v11.1).
There are still a bunch of warnings but they are all related to OpenGL being deprecated.

Fix Xcode auto-fixable issues

---

CMakeLists.txt

By setting `CMAKE_RUNTIME_OUTPUT_DIRECTORY` to `$<1:${CMAKE_BINARY_DIR}/bin>`
Without this, the resources did not end up into the SolveSpace.app file, causing a crash on startup (where it was unable to load the locales.txt file)
The reason is that the XCode project puts things into the "bin/Debug/SolveSpace.app" or "bin/Release/SolveSpace.app" folders (depending on the target), and some files ended up in "bin/SolveSpace.app" instead, this seems to fix the locales ending up in the wrong place, but I still see some files (libraries) ending up in "bin/Debug" or "bin/Release" folders.
Here is a list of them:
```
$ ls bin/Debug
libcairo.a               libpixman-1.a            libslvs.dylib
libdxfrw.a               libpng16d.a              libsolvespace-core.a
libflatbuffers.a …
```

Fix CMake Xcode generator.

---

src/srf/boolean.cpp

Union and difference are optimized by replacing the expression
`(!inShell && !inFace)`
which is equivqlent to
`(!inShell && !inSame && !inOpp)`
with
`outSide`
which is qeuivalent, since `SShell::Class::OUTSIDE` is the only remaining possibility.

Simplify UNION and DIFFERENCE boolean operations.

---

.travis.yml
.travis/build-debian.sh
.travis/install-debian.sh
.travis/install-macos.sh

- Fix invalid osx_image xcode8.2
- Drop depreceated sudo keyword
- Run debian build on bionic image & re-enable building with ui
- Split build into separate jobs & stages for better separation of concerns
Split out from #506 
We have two stages here:
- Test
- Deploy
Test runs the debian build. If that succeeds, we do OSX and later the Snap build in ```Deploy```.

Refactor Travis config

---

src/CMakeLists.txt

macOS build broke with 07992cecaaeeeb0584f3c655eaaf32ba09bd3e6d this fixes that.

Remove missing rendergl.cpp file from CMakeLists.txt

---

src/platform/guimac.mm

On macOS, when closing the preferences window, then clicking `Preferences` in the Menu, does not open the preferences window.
This PR fixes that.

Fix preferences not opening when closed on macOS

---

CHANGELOG.md
src/confscreen.cpp
src/constraint.cpp
src/mouse.cpp
src/solvespace.cpp
src/solvespace.h
src/ui.h

Here it is again, this time with config option.
Let me know if the default should be on or off, and if the variables / place in the preferences pane are fine with you.
The option does now also work on the angle constraint.

Adding config option to immediately edit dimensions

---

src/platform/guimac.mm

This is the last bug I have found on Catalina.
Tooltips are not closed when hovering off something.
The private API seems to have changed, and implementing tooltips seems to be a pain in the butt, so I checked for the availability of the method and fall back to the old method for now.

Fix tooltips not closing on macOS Catalina

---

src/render/rendergl1.cpp
src/solvespace.cpp
src/srf/surface.cpp
src/toolbar.cpp

Found when compiling with clang 9.

Fix eight trivial "implicit conversion 'double' to 'int'" warnings. NFC.

---

.travis.yml
.travis/deploy-snap.sh

dpl-snap only supports pushing one snap at a time.
Instead of many repetitive deploy statements, we use our own script to loop over the snaps to be released.

snap: Release snaps to store via script instead of snap provider

---

src/constraint.cpp

As promised, the fix for immediately editing reference dimensions.
The issue was that the editor was opened before redundant constraint check was done.

Fix immediate editing of reference constraints

---

.travis.yml

Running the build step with sudo necessitates running the deploy step with sudo too.
Otherwise, we face permission problems.

snap: Add missing sudo in Travis deploy step

---

pkg/snap/snap/snapcraft.yaml

Remove all files from snap that are already included in the base snap
or in any connected content snaps.
The main advantage is the massively reduced snap size:
From **~70 MB** down to **~6 MB**:
```shell
edge:      3.0~dcc80de7 2020-02-08 (10) 69MB -
installed:   3.0~b809e41a            (x1)  5MB -
```
solvespace-cli needs the gnome-3-28 extension to find its libraries. LD_LIBRARY_PATH wasn't getting modified on launch because the gnome extension was only applied to the GUI app "solvespace".

snap: Remove superfluous files from package & fix missing extension for cli

---

src/export.cpp
src/platform/guiwin.cpp
src/render/render.h
src/solvespace.cpp
src/textscreens.cpp

Found with /W4 by MSVC 2019 (Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28314)
A bunch of implicit casts 'double' to 'float' and one 'int64_t' to 'unsigned'.
.\src\platform\guiwin.cpp(1237): warning C4701: potentially uninitialized local variable 'cursorName' used
.\src\platform\guiwin.cpp(1237): warning C4703: potentially uninitialized local pointer variable 'cursorName' used
.\src\solvespace.cpp(805,30): warning C4456: declaration of 'gs' hides previous local declaration
.\src\solvespace.cpp(715,17): message : see declaration of 'gs'
.\src\solvespace.cpp(849,47): warning C4456: declaration of 'e' hides previous local declaration
.\src\solvespace.cpp(847,29): message : see declaration of 'e'
.\src\render\render.h(288,51): warning C4458: declaration of 'camera' hides class …

Fix some trivial warnings found by MSVC (NFC). And a bug with SpaceMouse.

---

src/CMakeLists.txt
src/solvespace.h

See:
https://github.com/solvespace/solvespace/issues/92#issuecomment-567831112
The problem was first introduced here:
https://github.com/solvespace/solvespace/commit/dabd57847edf142f145491175fb203455023d9d7
and later "fixed" here:
https://github.com/solvespace/solvespace/commit/f324477dd06c15022670a4486bf83be3abbf48b5
by setting the stack size to /STACK:33554432
Solvespace now starts up even with /STACK:554432
According to this:
https://en.cppreference.com/w/cpp/language/value_initialization
```
"2) if T is a class type with a default constructor that is neither user-provided nor deleted (that is, it may be a class with an implicitly-defined or defaulted default constructor), the object is zero-initialized and then it is default-initialized if it has a non-trivial default constructor; " …
```

Win32: Drastically reduce stack usage at startup. NFC?

---

src/render/rendergl3.cpp

Same warning and fix as in 16c5fa6889202f2059b52c4a89599910541dd1a0, but for `rendergl3.cpp`.

Fix two trivial implicit double to int conversion warnings. NFC

---

src/util.cpp

This should solve #490 
The problem was that the message box tries to split the `description` string after the first dot or colon, but if there is only a single dot at the very end of the string, when calling `isspace(*it)`, the value of `*it` is `\0` and crashes.

Solve crash when trying to show error with bad separator.

---

CMakeLists.txt

Force-vendor libraries on Win32 like on Apple and update ANGLE, fixing some Windows build envs

---

test/harness.cpp

This fixes tests when `__FILE__` produces output separated with `/` instead of `\`

Accept both slashes in test harness on Win32

---

CMakeLists.txt

Just GCC and Clang, I don't have a way to test MSVC behaviour.
Ref: #565

Force SSE2 floats for i686 targets

---

src/mouse.cpp

This was incorrectly capturing `r` by reference and using it after it left its scope. Changed to capture by value, and also explicitly capture `this` in case we were accidentally capturing any other scope variables by reference.
Fixes #571

Fix segfault in Remove Spline Point context menu

---

src/graphicswin.cpp
src/ui.h

This is to make them a bit easier to find, since the natural place to look for config options is somewhere like File->Preferences or Edit->Settings. On Mac the Configuration should be under the "App" menu but I'm not sure how to do that.

Add menu options for line styles / view / configuration

---

pkg/snap/snap/snapcraft.yaml

As per https://snapcraft.io/docs/snap-layouts,
bind-mounts significantly increase the startup time of the snap.
Use symlink instead for better performance.

snap: Use symlink instead of bind-mount for layout

---

pkg/snap/snap/snapcraft.yaml

Using gnome-3-34 gives us a newer stack in general
and also provides us with a sdk build-snap, so we don't need
to specify as many build-packages and stage-packages.
This makes the snap slimmer and delegates the responsibility
for security updates to the gnome platform snap for even more
packages.

snap: Upgrade from gnome-3-28 extension to gnome-3-34

---

src/group.cpp

fixes issue #549.
Might break some older files with those groups.

No extra copies of entities in Revolve and Helix groups.

---

src/group.cpp
src/sketch.h

Eliminates a crash due to copy numbers going over 1000.
May break some older files with constraints on lathed entities.

Eliminate some entity copies in lathe groups.

---

.travis.yml

arm64 builds on Travis are not yet fully mature and this
causes a high failure rate that is not caused by our code.
Continue building and deploying arm64 to the edge channel,
but don't consider the result for the success of the whole
build job.
Alleviates #587

Travis: allow Snap arm64 to fail

---

src/srf/triangulate.cpp

Redundant edges were culled by a function with O(n^2) time. The number of edges was 4xy so not needing to cull them increases frame rate on surfaces of degree 2x2 or higher while dragging.

Don't create redundant edges in UvGridTriangulate into.

---

src/srf/ratpoly.cpp

Don't report failed convergence when using cached U,V from ClosestPointTo. Add a separate message for when all efforts fail to converge.

No message if cached points to don't converge. Quiet the terminal.

---

src/srf/surface.cpp

This implements the change suggested in #481.  Performance gain with simple helical test models was 15-25 percent on current master. Gain is more apparent at lower chord tolerance.  Existing builds should not see any difference until they are told to use OpenMP. For GCC that just means passing -fopenmp.

Use OpenMP for triangulation

---

src/srf/triangulate.cpp

Produces a higher quality mesh in areas covered in quads by spitting the other way if needed to prevent angles over 90 degrees.

Split quads based on angle.

---

src/srf/surface.cpp

NFC:Use omp critical to simplify parallel triangulation.

---

src/solvespace.h

Should be more correct + snaps don't fail to build

Use C++ instead of C versions of standard library headers

---

src/srf/triangulate.cpp

When checking the dot product of the tangents `tu` and `tv` to decide in which direction to split a quad compare it to to `LENGTH_EPS` instead of zero to avoid alternating triangle "orientations" when the tangents are orthogonal (revolve, lathe etc.). This improves the quality of the resulting triangle mesh.
Before:
After:
Model:
[LatheSpline.zip](https://github.com/solvespace/solvespace/files/4618604/LatheSpline.zip)

 Improve triangle mesh (splitting of quads based on angle).

---

src/srf/boolean.cpp
src/srf/surface.h

Use OpenMP to  run SShell::CopySurfacesTrimAgainst() and SShell::MakeClassifyingBsps() in parallel at the surface level.

Bring some parallelism to boolean code

---

src/srf/boolean.cpp

This is similar to the corrections in #473 but affects calculation of edge normals in boolean.cpp. I don't know a specific issue that this fixes, so I'd like to hold off merging until we have an example issue that it corrects. Such problems are likely to occur with booleans involving Helix extrusions.

Fix SSurface::EdgeNormalsWithinSurface() to handle non-orthogonal u,v derivatives correctly.

---

src/srf/ratpoly.cpp
src/srf/surface.cpp
src/srf/surface.h
src/srf/triangulate.cpp

…4 segments and forcing grid triangulation to use a minimum of 4x4 quads. This helps with issue #489. Also add a max_dt parameter for PWL creation and use that for helical edges.

Better helical triangulation #489 and #550 fixed.

---

.gitmodules
.travis/install-debian.sh
CMakeLists.txt
README.md
pkg/snap/snap/snapcraft.yaml
src/CMakeLists.txt
src/platform/platform.cpp

Use mimalloc for {Alloc,FreeAll}Temporary()

---

CMakeLists.txt

currently the static mimalloc library built by solvespace is being installed
this should stop it from being installed

Dont install mimalloc

---

src/srf/curve.cpp
src/srf/surface.cpp
src/srf/triangulate.cpp

Use the grid spacing algorithm for helical curve PWL creation.
This makes the grid and trim curves have similar spacing.

Fix #647 Helix mesh defects.

---

src/srf/triangulate.cpp

A simple optimization in triangulation code. Tested on several models.

NFC: Remove a redundant pass over all verticies in ear triangulation.

---

src/srf/raycast.cpp

The surface was being modified in SSurfaceSplitInHalf. Make a local copy instead.

Fix #656 by making SSurface::SplitInHalf thread safe.

---

src/constrainteq.cpp
src/describescreen.cpp
src/sketch.h
src/style.cpp
src/textscreens.cpp
src/ui.h

Improve text screen for a selected constraint:
* Show the type of a constraint.
* Show the workplane a constraint is in, for constraints which can be both projected to workplane or be free in 3d space.
* Clearly distinguish reference from non-reference constraints.
* Add a checkbox for toggling the reference option.
* When showing requests a constraint applies to, highlight on hover the specific entity being constrained, not just the first one.
Improve text screen for a selected entity:
* Add a link to its request, unless it's the first entity in that request (which would just select the same entity again).
* Add a link to its group.
* Add a link to its workplane.
* Add a link to its style; and hide the style row for entities that aren't stylable.
* Show constraints and measurements …

Improve text screens for selected constraint and entity

---

src/drawentity.cpp
src/entity.cpp
src/group.cpp
src/sketch.h
src/srf/surface.cpp

Create a new copy type for faces that includes the translation aspect of helical extrusions. Also swap the end remappings when the shell is inside out - this was also affecting some Revolve extrusions.

Fix issue659 - Problems constraining to ends of Helix.

---

src/polygon.h
src/srf/triangulate.cpp

This is still experimental. I noticed that ear triangulation calls RemoveTagged() for every ear and that function scans (copies?) the entire list of verticies. It also has to check IsEar() for the adjacent verticies afterward. I figured we can make a pass looking for chains of ears that form a sort of meta-ear and triangulate that independently, and only make one call to RemoveTagged() to dispose all those ears. This runs prior to the existing triangulation code (and only for flat surfaces) so it might be faster overall for very complex surfaces. It does tend to make better-formed triangles.
Still some bugs and odd cases to figure out.
The logic is not clear yet.
Haven't proven any practical benefit like speed improvement.
One odd thing I did notice. If you look at the mesh for a circle …

WIP:  Triangle Fans

---

src/srf/boolean.cpp
src/srf/ratpoly.cpp
src/srf/surface.h
src/srf/surfinter.cpp

I'd like to get input on this from @jwesthues  @ruevs and @Evil-Spirit 
The code in Boolean tries to intersect a curve with a surface. It uses the PWL representation of the curve (the more general case) and the 2 surfaces it trims. To do the intersection it calls SSurface::PointOnSurfaces() which finds the U,V intersection of the 3 surfaces. I noticed that function will not converge (it gives up) if 2 of the surfaces are tangent along the curve, which is the case for Lathe and Helical surfaces joined every 90 or less degrees. In that case we always have an exact representation of the curve, so I created a new function to intersect an exact curve with a surface which can be used in the (common) special case that we have and exact curve. I thought this may result in better accuracy finding …

NURBS boolean improvement.

---

src/srf/boolean.cpp

Together these reduce Generate on a complex sketch from 50 seconds to 30. The first replaces 2 nested for loops with one loop and a lookup by ID. The second removes an OMP critical from a loop - puts that update in a non-parallel loop by itself.

NFC: Performance optimizations

---

src/confscreen.cpp
src/export.cpp
src/exportvector.cpp
src/platform/entrycli.cpp
src/solvespace.cpp
src/solvespace.h
src/ui.h

Produces non-zero diffs for EPS, PDF, and SVG:
<details>
<summary>EPS</summary>
```diff
diff --git a/no.eps b/yes.eps
index 3d6a0a9..86fcb68 100644
--- a/no.eps
+++ b/yes.eps
@@ -9,6 +9,18 @@
gsave
+0.000 0.400 0.000 setrgbcolor
+newpath
+    0.000 0.000 moveto
+    176.882 0.000 lineto
+    176.882 159.307 lineto
+    0.000 159.307 lineto
+    closepath
+gsave fill grestore
+1 setlinejoin
+1 setlinecap
+0.177 setlinewidth
+gsave stroke grestore
newpath
162.709 14.173 moveto
162.709 145.134 lineto
```
</details>
<details>
<summary>PDF</summary>
```diff
diff --git a/no.pdf b/yes.pdf
index 1a6d964..3d231c0 100644
--- a/no.pdf
+++ b/yes.pdf
@@ -30,6 +30,15 @@ endobj
5 0 obj
<< /Length 6 0 R >>
stream
+1 J 1 j
+0.000 0.400 0.000 RG
+0.000 0.400 0.000 rg
+0.177 w
+0.000 0.000 m
+176.882 0.000 …
```

Optionally export background colour in vector files

---

src/graphicswin.cpp

FIxes issue 197. Opted for EnsureValidActive() rather than ClearSuper() so selections will remain selected.

Update Menu checkboxes after failed workplane activation. Fixes 197.

---

src/drawentity.cpp

In the recent select-for-dragging fix I misidentified a copy type as non-draggable and it made linked items in an assembly not draggable.

Fix 699: Allow dragging linked objects in an assembly.

---

src/platform/entrycli.cpp

This fixes issue #499. The --view option changes projUp and projRight. For --view to affect the camera, the camera needs to be initialized using these values.

solvespace-cli: Fix --view

---

src/platform/entrycli.cpp

This is for issue #499. A recent commit fixed the --view selection but it was still not centered, nor were the various direction options working correctly.

Fix view centering for cli thumbnail function.

---

src/srf/surface.h
src/srf/surfinter.cpp

When a plane coinsides with a seam we need to copy that trim curve. The existing curve belongs to the original shell surfaces and an intersection is otherwise not found. Closes #540.

Create intersection curves from existing ones.

---

src/platform/entrygui.cpp
src/platform/platform.cpp

`GetSaveFileNameA` `OPENFILENAMEA` does not like UNC ( "\\\\?\\C:\\..." ) file prefixes in `lpstrFile`.
Work around it by not `Expand`-ing parameters passed on the command line too early.
The only user visible change is that "File|Open Recent" will show items as they
were passed instead of expanded to full path for example:
"..\..\NURBSTests\Intersection2.slvs"
Fixes: https://github.com/solvespace/solvespace/issues/622

Win32: Fix "File|Open...", "Save" and "Save As" when a command line argument is used.

---

src/draw.cpp

`window` is a `nullptr` with guinone.cpp - avoid dereferencing it.
Fixes: https://github.com/solvespace/solvespace/issues/567

Fix crash in solvespace-cli

---

.travis.yml
.travis/build-windows.sh
.travis/install-windows.sh

Mimic the appveyor cfg without the artifact deployment.
Also upgrade to Visual Studio 2017/v141 toolset.

Travis: add windows target

---

.travis.yml
.travis/sign-macos.sh

This removes the old OSX build, and fixes the repo argument (it was still set to my fork vespakoen/solvespace)
I also used the api_key that was set in the old OSX build, not sure if this will work though...
This PR is dependent on #747

Update .travis.yml for macOS build

---

src/srf/ratpoly.cpp
src/srf/surface.h

@ruevs This is probably the clearest and cleanest we can get. What do you think?

Avoid zero tangnet vectors on degenerate NURBS edges. Fixes #652

---

src/platform/guimac.mm

This seems to solve a flickering issue.
Should I be using the `macOS:` prefix?

macOS: add NSOpenGLPFADoubleBuffer to NSOpenGLPixelFormatAttribute

---

.travis.yml
.travis/build-macos.sh
.travis/sign-macos.sh

- Fixing travis lint problems
- Re-enable multi core building for macOS
- Quote variables
I was wondering why signing wasn't working, only to find out that build secrets are not exposed to pull request builds (duhhh)
But these changes are probably helpful anyways.

Travis: fixing travis lint problems, re-enable multi core building for macOS, quote variables

---

CMakeLists.txt

LTO/IPO with non-Intel compilers on Linux requires policy CMP0069 to be set to NEW.
Set it explicitly until cmake_minimum_required is raised to >= 3.9
Also explicitly check whether the current environment actually supports IPO.

CMake: fix LTO on Linux

---

.travis.yml
.travis/build-macos.sh
.travis/build-windows.sh
.travis/sign-macos.sh

This will release every commit on the master branch to the "edge" tag, it also:
- Fixes windows build type not being picked up
- Revert `cleanup: false` back to `skip_cleanup: true` (to fix snap releases)
- Waits 10 seconds to get notarize_uuid for macOS since it would sometimes fail
- Build test stages in `Debug` mode and deploy stages in `RelWithDebInfo` mode

Travis: release macOS and Windows edge builds

---

src/exportstep.cpp

The implementation may be sub-optimal, since the colour and alpha is defined for each NURBS surface instead of on group level, but the STEP export currently does not represent group structure at all and I am not familiar with the format in order to change this.
Fixes: https://github.com/solvespace/solvespace/issues/452

STEP Export: include colors and alpha

---

pkg/snap/snap/snapcraft.yaml

`libgomp` is provided by the gnome platform snap:
```shell
ldd solvespace | grep gomp
libgomp.so.1 => /snap/solvespace/x2/gnome-platform/usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f752d0b7000)
```
LTO seems to be there as well:
```shell
readelf -Wa solvespace | grep lto
752: 000000000050083d     1 OBJECT  LOCAL  DEFAULT   28 _ZStL8__ioinit.lto_priv.860
753: 000000000050083c     1 OBJECT  LOCAL  DEFAULT   28 _ZStL8__ioinit.lto_priv.859
888: 00000000005012e1     1 OBJECT  LOCAL  DEFAULT   28 _ZStL8__ioinit.lto_priv.742
889: 00000000005012e0     1 OBJECT  LOCAL  DEFAULT   28 _ZStL8__ioinit.lto_priv.741
[...]
```
Need to check:

snap: enable OpenMP and LTO

---

CMakeLists.txt

CMake: Give ENABLE_LTO a default and a description so it shows up in cmake-gui

---

src/exportstep.cpp

Make the color export work in KiCAD and Horison EDA which do not support
transparency.
Fixes: https://github.com/solvespace/solvespace/issues/452
https://github.com/solvespace/solvespace/pull/763

STEP Export: fix colors in  Horison EDA and probaly KiCAD

---

src/srf/boolean.cpp
src/srf/surface.h

Two commits. One fixes the huge performance regression and is only a little slower than prior to the regression. 18.5 seconds compared to 193 seconds. Prior to the NURBS fix that same test took a bit over 15 seconds. That seems reasonable for adding more code in order to fix an issue.  The second commit here adds OpenMP parallelism to the same part of the code and bring the test down to 11.x seconds.

Vertex split

---

src/srf/boolean.cpp

Makes boolean operations a bit faster.

Add OpenMP parallel for to SShell::CopyCurvesSplitAgainst

---

CMakeLists.txt
exposed/CMakeLists.txt
src/CMakeLists.txt
test/CMakeLists.txt

Previously sanitizer flags were set unconditionally for all code, including that of external libraries.
Set them only for targets in src/, tests/ and exposed/.
Unfortunately, the linker equivalent to add_compile_options,
add_link_options, is only available for CMake version >= 3.13.
So add the sanitizer flags manually to each target's linker options.
Should help with #766

CMake: use sanitizer flags for internal targets only

---

src/dsc.h
src/util.cpp

Profiling with MSVC 2019 showed that many of the Vector methods are on a critical path (not surprising). They are changed to be inline and unnecessary temporaries are removed.
On the example below generate times decreased from 102s. to 64s.
At the same time the executable size shrank from 5569536 to 5150208 bytes in release mode (with global optimizations).
This should not stop us from working on optimizing inner loops e.g. https://github.com/solvespace/solvespace/issues/759 .
[Test model](https://github.com/solvespace/solvespace/files/5414683/PrismConeNURBSNormalsTangents300.zip)
Profiling results:
[20201021_Profiling_Before.txt](https://github.com/solvespace/solvespace/files/5416268/20201021_Profiling_Before.txt)
[20201021_ProfilingAfterVectorInline1.txt](https://github.com/solvespace/so …

Performance optimization of the Vector class

---

CMakeLists.txt
exposed/CMakeLists.txt
src/CMakeLists.txt
test/CMakeLists.txt

This reverts commit 68b1abf77f5c8858659a51b8bdbf760effb53b66.
The warnings are valuable and shouldn't be cast aside.
As of 8f509f1, we special case macOS and don't set -fno-sanitize-recover
to allow CI to succeed.
In the future, this could be made stricter again by only suppressing
known bugs, which ideally should also be fixed or reported upstream.

Revert "CMake: use sanitizer flags for internal targets only"

---

src/srf/ratpoly.cpp

This is another small profiling driven optimization.
Moving the initialization of `const double *c` as part of the definition also helps with the generated assembler.

Performance: inline the Bernstein functions

---

src/textwin.cpp

- Scrolling with the scrollbar now works properly.
- Do not scroll with the mouse wheel while an edit field is active in the property browser.
Fixes: https://github.com/solvespace/solvespace/issues/782

UI: Fix the Property Browser window scrollbar

---

src/textwin.cpp
src/ui.h

Fixes issue #779 by
1) increasing max rows in the text window
2) adding a marker at the end so we know what's happening next time someone hits it.

Add end marker to text window and increase max rows.

---

.travis.yml
.travis/tag-edge.sh

With the recent Travis changes, we prevented the deploy
stage from running for tagged commits as branch=tag
for tagged commits. Fix this by also running deploy for
tagged commits.
Furthermore, clean up .travis.yml by pulling the edge
tagging logic into a separate script.
A logic change is introduced to prevent git tag --force being
run on set tags as this would turn annotated tags into
lightweight tags.

Travis: deploy tagged commits & edge tagging fixes

---

.travis.yml

Our implicit deploy conditions were previously only met by untagged commits
on master. As the stage conditions filter everything except branch = master
and tagged commits, we can just use all_branches: true to also deploy tagged
builds.
Also clean up the snap deploy sections.

Travis: deploy tagged & master commits to GitHub

---

src/exportstep.cpp

Found by clang 11. They are a potential problem.
[ 21%] Building CXX object src/CMakeFiles/solvespace-core.dir/exportstep.cpp.obj
.\src\exportstep.cpp:293:61: warning: unsequenced modification and access to 'id'      [-Wunsequenced]
fprintf(f, "#%d=FILL_AREA_STYLE_COLOUR('',#%d);\n", ++id, id - 1);
^     ~~
.\src\exportstep.cpp:294:56: warning: unsequenced modification and access to 'id'      [-Wunsequenced]
fprintf(f, "#%d=FILL_AREA_STYLE('',(#%d));\n", ++id, id - 1);
^     ~~
.\src\exportstep.cpp:295:59: warning: unsequenced modification and access to 'id'      [-Wunsequenced]
fprintf(f, "#%d=SURFACE_STYLE_FILL_AREA(#%d);\n", ++id, id - 1);
^     ~~
.\src\exportstep.cpp:297:98: warning: unsequenced modification and access to 'id'      [-Wunsequenced]
fprintf(f, …

Fix unsequenced modification and access warnings.

---

.travis.yml
.travis/build-snap.sh
.travis/deploy-snap.sh
.travis/install-snap.sh

With arm64-graviton2 now providing full VM virtualization, LXD containers
can be used to build snaps on all architectures.
This is beneficial for us as having snapcraft manage the whole build
environment is likely to yield better/more consistent results than
running the builds on the Travis images directly.
Also use snapcraft upload instead of depreciated push.
My hope is that this gets rid of the slightly mysterious `/tmp/snapcraft-2494/run-1.sh: 88: /tmp/snapcraft-2494/run-1.sh: Syntax error: "(" unexpected` build failures.

Travis: build snaps in LXD containers

---

.gitmodules
.travis/install-ubuntu.sh
CHANGELOG.md
CMakeLists.txt
README.md
pkg/snap/snap/snapcraft.yaml
src/CMakeLists.txt
src/export.cpp
src/platform/gui.cpp
src/solvespace.h

It was added in 3a3a275 as a potential way to export colorful meshes
to Horizon EDA but ended up being supported only by SolveSpace. Since no
software can consume the exported q3do files the feature is superfluous.
See https://github.com/solvespace/solvespace/issues/795 for details.

 Remove Q3DO export and flatbuffers

---

src/platform/guiwin.cpp

On scroll wheel events convert the mouse coordinates from screen to client
area so that scroll wheel zooming remains centered irrespective of the
window position.
Fixes https://github.com/solvespace/solvespace/issues/806

Win32: Mouse wheel zooming always remains properly centered

---

src/textscreens.cpp

... is enabled.
"err" was first introduced in c2c26e95adb to indicate sketches that may cause
problems in the subsequent 3D groups. But is makes sense not to display the
error if the "check sketch for closed contour" option is turned off. The user
obviously does not want to be warned.
Based on a suggestion in https://github.com/solvespace/solvespace/issues/819

UI: Display "err" in the property browser only if "check sketch for closed contour"

---

src/platform/guiwin.cpp

...which can be zero.
Fixes: https://github.com/solvespace/solvespace/issues/817

Win32: Remove sscheck on SetScrollInfo - it returns the scrollbar position

---

src/platform/guiwin.cpp

The return value of these functions is not an error code and according to
the Win32 API documentation they can not affect `GetLastError`.
Calling sscheck on them normally does not fail since it does
SetLastError(0) before running the checked expression and only then
GetLastError(). However in issue 817 a user discovered that when running
"DisplayFusion" software GetLastError does return an error and SolveSpace
closes.
So while not a strict bug-fix this is a "correctness improvement" for
SolveSpace and works around a possible bug in DisplayFusion.
Similarly the return value of Reg*** functions is now compared to
ERROR_SUCCESS which is zero. Before the sschecks were strictly wrong but
did not cause problems for the same reason as above.

Win32: Remove sscheck on IsWindowVisible and ShowWindow

---

src/mouse.cpp
src/platform/platform.h

The default font is BitstreamVeraSans-Roman-builtin.ttf since 94b26ddfac0c,
but the URI was incorrectly set.
Fixes: https://github.com/solvespace/solvespace/issues/821

Set the default font for text objects correctly.

---

src/clipboard.cpp

I noticed, when paste-rotating my sketch at 90 degrees, that the vertical and horizontal constraints didn't get updated.
This fixes it.
Should we also take multiples of "X" in: `90+(X*180)`? and negative numbers? (sorry, couldn't explain it better).

Swap vertical and horizontal constraints when rotating 90/270 degrees

---

src/solvespace.cpp

This removes the shortcut for Stop tracing, and maps it to Save As instead.
I have been modelling a lot yesterday and actually lost 2 models because I am used to use the Cmd+Shift+S shortcut for Save As.
However, (very unnoticeable) it actually prompts to save a CSV for the trace.
The result, you are left with an empty CSV file in stead of the model.
I removed the Stop Tracing shortcut (maybe we can assign something else to it?)
**Save As** is now `Ctrl ` + `Shift` + `S` for Linux, `Cmd` + `Shift` + `S` and macOS, and `Ctrl` + `F12` on Windows

Fix Save As shortcut

---

src/file.cpp
src/platform/gui.h
src/platform/guigtk.cpp
src/platform/guimac.mm
src/platform/guiwin.cpp
src/platform/platform.cpp
src/solvespace.cpp
test/core/path/test.cpp

Example: ![screenshot](https://user-images.githubusercontent.com/6709544/77234221-e8a69680-6bac-11ea-93a5-96881e40cd1c.png)
Tested on Windows only, with the assumption that other platforms' `Platform::FileDialog` behaves the same.
Ref: #538

Pre-populate file dialogs with sensible defaults

---

CHANGELOG.md
src/mouse.cpp
src/platform/guigtk.cpp
src/platform/guimac.mm
src/platform/guiwin.cpp
src/textwin.cpp
src/ui.h

This is for macOS only at the moment, and probably breaks scrolling on windows and linux.
This is just an initial experiment, tested with a trackpad and an external mouse with a scroll wheel on macOS.
I will test this on windows and linux and will move the calculations to the platform specific code.
EDIT: Damn.. looks like my editor decided to format the whole mouse.cpp file...

Fix zoom not working while scrolling slowly on macOS, take WHEEL_DELTA into account on Windows.

---

src/graphicswin.cpp

I found that snap to grid was still not working in some cases, looking at the code, I think this line:
```
SS.GW.ClearPending()
```
Got added unintentionally.
Also, `SS.GW.ClearSelection();` already seems to call `SS.GW.Invalidate();`, so I removed the `SS.GW.Invalidate();` call as well.
After this change snap to grid seems to be working fine.
I wonder if the pending list should still be cleared though, perhaps after the call to ClearSelection.
Will look into this.
To test the broken snap to grid, turn the grid on, draw a rectangle, try to snap each corner, some (might) fail.

Fix snap to grid not working in some situations

---

src/draw.cpp
src/drawentity.cpp

I noticed that sometimes normals would get selected even when I didn't select them.
So I added some code to visualise the bounding boxes, which showed me this:
Notice the little yellow dots around the center of the drawing, these are the normals of the arcs.
I then also noticed that when in "3d view", the selection didn't work sometimes, this was caused by the selection marquee only having a "depth" of 1 ... "unit" ?
This PR fixes both of these things, I wonder though, if for the BBox we should add a "FlatOverlap / Overlap2d" check that ignores the Z value, right now I am using the VERY_NEGATIVE and VERY_POSITIVE values for the Z range which is not optimal.
Here is the code for drawing the BBoxes by the way if anyone is interested:
```
+        // Draw the bboxes
+        Entity *e;
+ …
```

Fix selection bugs

---

src/clipboard.cpp
src/constraint.cpp
src/sketch.h

I found some more oddities with paste transformed.
I am hoping I can solve them and am planning to add some new tests for these as well.
~~The first thing I noticed is that rotating happens in counter clockwise direction (at least in the workplane that is opened by default when starting a new sketch)~~ stupid me, scrap that.
The second thing I noticed is that when flipping an arc with tangent constraints, the arc gets inverted, removing the constraints fixes this, but there should be a better way to actually invert the arc which I haven't found yet.
Here is a little sketch to try out.
[rotate-and-flip-me.slvs.zip](https://github.com/solvespace/solvespace/files/5621762/rotate-and-flip-me.slvs.zip)

Clipboard fixes

---

README.md

Looks better when zooming in a lot - the SVG is rendered perfectly sharp while browsers "smooth" the PNG (bicubic,, Lanczos or such resampling).

README.md: Use the SVG icon with a relative path.

---

src/platform/guiwin.cpp

On Windows SolveSpace 2.3 uses a plain dialog for `SolveSpace::Error` and
`SolveSpace::Message` with no icon and no system beep. After the GUI
abstraction was reworked this changed to the default system message boxes
(using MessageBoxIndirectW) that play the "Default Beep" sound and show
red "X" and blue "i" icons respectively.
The beep is annoying since the error and message dialogs are used often to
show required conditions for constraints, new groups and other behaviors.
This disables the beep and uses the SolveSpace icon.
Fixes: 719

Win32: Avoid the "Default Beep" sound in "Еrror" and "Message" dialogs

---

src/drawentity.cpp
src/toolbar.cpp

The toolbar height is
`int fudge = 8;`
`int h = 32*18 + 3*16 + fudge;`
It means 18 icons 32 pixels each and 3 separators 16 pixels each.
`32*18 + 3*16 + 8 = 632`
`36*16 + 3*16 + 8 = 632`
See these correct increases of the toolbar height:
https://github.com/ruevs/solvespace/blame/bf4de993cbc752cd063bd7dbaa8ef44b36ec13e4/toolbar.cpp#L97
https://github.com/ruevs/solvespace/blame/fe2ea5d5e1c0a361c78248521fc3cff06ab322a9/toolbar.cpp#L103
https://github.com/ruevs/solvespace/blame/ef5db2132e871e12c667bc2147e94c2cabf37729/src/toolbar.cpp#L112
https://github.com/ruevs/solvespace/blame/ca2aad7fea14b09cd4df39b9a4628781f76624c7/src/toolbar.cpp#L145
And then these incorrect ones:
https://github.com/ruevs/solvespace/blame/3e3ccdca8d6c66080078c46c274cbde645f43cf4/src/toolbar.cpp#L156 …

Correct toolbar height calculation

---

src/solvespace.cpp

Looking for feedback on this one. It relates to issue #835. I don't know if "0..." is a good thing. We could also figure out the minimum number of digits to display a non-zero value and override the setting (I think that's preferable).
Thoughts?

WIP: Don't show small values as 0.0

---

src/mouse.cpp

@ruevs @phkahler   I don't think this Invalidate() is necessary on Windows and also fixes Issue #720.  Since this is in the SS core vs. platform can you please both review and comment on impact on Linux and Mac?

do not Invalidate() dragging new points to prevent Windows refresh glitches

---

res/locales/de_DE.po
res/locales/en_US.po
res/locales/fr_FR.po
res/locales/ru_RU.po
res/locales/uk_UA.po
res/locales/zh_CN.po
res/messages.pot
src/file.cpp

Fixes: https://github.com/solvespace/solvespace/issues/918
The problem was that here:
https://github.com/solvespace/solvespace/blob/11a8a0abd5e21a0da6c818674f8b4b657a401a6c/src/file.cpp#L480
we cleared all groups. Then we tried to read an empty file and therefore this `while` exited immediately:
https://github.com/solvespace/solvespace/blob/11a8a0abd5e21a0da6c818674f8b4b657a401a6c/src/file.cpp#L487
and we came to here:
https://github.com/solvespace/solvespace/blob/11a8a0abd5e21a0da6c818674f8b4b657a401a6c/src/file.cpp#L548
where there was no `fileLoadError` and thus we were left with no groups, and so this assert failed:
https://github.com/solvespace/solvespace/blob/11a8a0abd5e21a0da6c818674f8b4b657a401a6c/src/graphicswin.cpp#L394
since is is not allowed to have no groups :-)

Fix a crash when opening an empty file.

---

src/describescreen.cpp

This addresses #863
When toggling reference dimension for an over constrained sketch mark group dirty to force a solve.  To test this PR use the over constrained 3-4-5 right triangle  [test-over.zip](https://github.com/solvespace/solvespace/files/5939160/test-over.zip).  Select the reference dimension and toggle it back and forth using the checkbox in the property browser.  With this patch the display should refresh as expected from red to black background and back.  This works by marking the changed group dirty so SS will recheck for redundant constraints.

mark group dirty when toggling reference dimension

---

src/constraint.cpp

This PR adds calls to `UndoRemember` before auto-removing constraints when adding midpoint or symmetric constraints.  The subsequent call to `AddConstraint` is changed to `rememberForUndo=false` in order to prevent requiring the user to undo twice to return to the starting state.
Fixes #928

remember auto-removed constraints for undo

---

src/graphicswin.cpp
src/mouse.cpp

Currently attempting to toggle construction geometry while drawing results in an error dialog. This PR enables the construction geometry toggle command ('g' key) to work while drawing lines, rectangles, arcs, circles, and cubics.
I feel this is an improvement over the error dialog and is useful when sketching.

permit construction geometry toggle while drawing

---

src/export.cpp
src/exportvector.cpp

This PR fixes #904 (and maybe #518).  There were two problems:
1. There was no definition for Style::NO_STYLE in the header
2. The styling was being set at the SBezierLoopSet level vs the SBezierLoop so loops in the set were all being styled the same.

Fix incorrect styling on SVG export

---

src/mouse.cpp

This fixes handling of the shift and ctrl modifiers for dragging. There are many code paths in the mouse move handling code and some improperly skip necessary steps.
The were several code paths when handling mouse movement that skipped updating the dragged points which suppressed screen updates.
It was possible for the shift / ctrl drag rotation vector to be empty in some cases, like at the start of a drag, nulling out the rotation.
the code that prevented the rotation vector from being degenerate at the start of the drag also prevented starting a drag with ctrl down as noted in issue #865
This PR also separate the extraLine tracking code from the point dragging code for clarity.

Fix problems with ctrl/shift key drag modifiers

---

src/describescreen.cpp

When two points are selected in addition to their distance show the X, Y and Z components of it in the text window.
Implements #936

UI: Show XYZ distance components in the text window for two points

---

src/constraint.cpp
src/sketch.h

This fixes a regression introduced in  96958f466395148ee7f0a252222a2a27e7345c22 (https://github.com/solvespace/solvespace/pull/833.)
Three `return` statements got "swallowed" by the newly created functions.
(e.g .https://github.com/solvespace/solvespace/commit/96958f466395148ee7f0a252222a2a27e7345c22#diff-49abc03ed071148c0ebae0c64aafb625fa6223135f77aeecdb47dab4cf8b940cL638 )
Because of this it was possible to constrain arcs and cubics tangent to each other or line segments, without them sharing an endpoint.
This kind of worked, but always chose the "starting" points of the curves and lines. In the future this can be turned into a feature. See the discussion in #937.

Fix tangent constraints of curves.

---

src/platform/guigtk.cpp

Gdk::Cursor::create(Gdk::HAND1) yields a hand cursor more appropriate for "grabbing" vs. pointing.  Use the recommended (non-deprecated) create by name API to get a "pointer" hand cursor for link text in the text window.  This more closely matches Windows and is easier to use.
"grabbing" hand
"pointer" hand

Use better pointer cursor for link text on GTK

---

src/platform/guiwin.cpp

#958 notes the hitting Esc does not cancel an edit as it does on Linux.  This PR hides the editor on Esc.

Hide editor window when user hits Esc on Windows

---

src/drawentity.cpp
src/export.cpp
src/exportvector.cpp
src/sketch.h
src/style.cpp

Primarily, this enables the user to export of construction entities in 2D views such as SVG and PDF as noted in #682. Previously construction entities were always skipped. The "export these objects" is now available for all default styles. One may turn off export of constraints or the inactive groups for example.  Because export of construction entities is no longer blocked export option for custom styles also works for them.
This also adds the exportable flag to the factory defaults (so it can be reset) and support for saving the exportable option for default styles in the configuration. Construction entities with custom styles respect this option as well.  
This also addresses a problem with missing contour fill for exported SVG.
To test this try exporting a sketch with construction …

Add exportable option to default styles

---

src/drawentity.cpp

This PR is a companion to #946 which corrects unstyled construction entities when exported as Beziers.  This does the same but when exporting edges.  It partially addresses #967

Export correct style for construction entities for when exporting edges

---

src/style.cpp

When reloading factory default styles redraw the graphics window.  This was noted in a comment to #682,

Trigger redraw on load factory default styles

---

src/dsc.h

Major performance improvement on GCC with libstdc++, see my comments in #939. Relates to discussion in #932.
All tests passed, nothing interesting in memcheck showed up.
I think this belongs in 3.0 and is obvious enough.
I've tried to use `std::move_backwards` but it didn't look better.

Fix pathologically slow translate groups on Linux

---

src/sketch.h
src/style.cpp

This PR saves the stipple settings for default styles to the configuration and closes #957.

Save stipple settings for default styles to config

---

.github/workflows/cd.yml

ARM64 builds in GitHub Actions fail with 
```shell
error: cannot pack "/data/prime": mksquashfs call failed: signal: illegal instruction (core dumped)
```
Lock the qemu image to a specific version that is known to work. Inspired by https://github.com/diddlesnaps/snapcraft-multiarch-action/commit/3fa0c51286443a8dad3be126d1f348bb01c17042

CI: Lock qemu version to known working

---

src/platform/guigtk.cpp

This resolves the issue I discussed on the IRC channel where Blender worked but Solvespace didn't while both use libspnav.
I'm also strongly proposing this for 3.0.
```
E.g. for when you have more than one user logged in, in which case
spacenavd works only for the first of those X11 displays.
We try to do it the old way first, so there should be no regressions.
Also fixes storing non-booleans in bool variables.
```

GTK: make spacenavd work through its socket, too

---

src/platform/guiwin.cpp

On windows 10 the open/save dialogue box has an minor error, and I believe I fixed it. 
When "Open" is selected from the menu, the title of the dialogue box says "SolveSpace - Save File" and the entered file name is "united". My fix correctly titles the dialoged box, and leaves the address bar blank when a file is being opened because "united" is only needed as a default name when a file being saved. 
I found that class FileDialogImplWin32 from guiwin.cpp contains two if statements for "isSaveDialog". This is redundant. I removed the first where the title was originally set, but not working. I then set the title in the second if statement and moved the 'if isEmpty'' to this section.

minor fix open/save dialogue on windows

---

src/confscreen.cpp
src/export.cpp

This closes #986.  The computed lighting value when ambient lighting value == 1.0 needed to be clamped to 1.0 in order to achieve flat shading as expected.
Also, this fixes the Printf format for the ambient lighting entry on the configuration screen.  This was causing strange behavior when attempting to edit the ambient lighting value on Windows.  Oddly this didn't seem
to affect Linux.

Clamp lighting value on export to fix flat colors

---

src/mouse.cpp

Right click can be used to end sketching of new lines and cubics as a convenient alternative to ESC.  This PR extends this feature to work when sketching rectangles, circles, arcs, ttf text and images as well.  Currently right clicking while sketching, say a rectangle, just pops up a context menu with one option, "Select All".  While choosing Select All does work I can't figure out why that would be useful in the middle of sketching.
I've been sitting on this for a while because I wasn't sure if this was of general interest.  My fingers have gotten very used to the right click feature for lines and cubics so I thought I would submit to see others think.

Allow right click to end sketching of all entities

---

.github/scripts/build-macos.sh
.github/scripts/install-macos.sh
.github/scripts/sign-macos.sh
.github/workflows/cd.yml
.github/workflows/test.yml
CMakeLists.txt
cmake/libpng-macos-arm64.patch
res/CMakeLists.txt
src/CMakeLists.txt

This is another attempt at #851
1) I had to use the `dev` branch from mimalloc, and apply this patch on top of it https://github.com/microsoft/mimalloc/pull/346
Collecting all the patches for M1 support seems to be unreasonable because they are so many, I think we will just have to wait for the dev branch to merge into stable and use (the latest commit on) the dev for the time being.
2) OpenMP is linked dynamically again, I am now simply downloading the compiled libraries from where homebrew stores them for our CI, so we don't have to maintain a OpenMP fork / add a new submodule.
Using `brew install libomp` won't work when compiling arm64 on x86_64 hardware (the github CI) since homebrew determines what to download based on the hardware.
3) Instead of forking libpng, I included the …

Apple M1 arm64 support simplified

---

src/graphicswin.cpp

Fixes issue #495
I had a 100% reliable repro locally (as described [here](https://github.com/solvespace/solvespace/issues/495#issuecomment-813023035)) and this change fixes it for me, I am no longer able to reproduce the assertion. There might be a better way to fix it that could avoid similar problems in the future (change how the lambdas capture, rework how PopulateMenuWithPathnames and onTrigger work?) but I'm not familiar enough with the codebase to make that judgement, and this seems to do the trick!

Copy path to avoid it being invalidated by OkayToStartNewFile()

---

.github/scripts/sign-macos.sh

Looks like I forgot to update this path, and that is causing the CI to fail at the moment.
@phkahler I also looked at the libpng patch, but that already seems to only be applied on macOS, so I think you can go into the submodule and run `git stash` or something to get rid of the changes that were made there

Correct libomp.dylib path in sign-macos.sh script

---

.github/scripts/sign-macos.sh

I cannot test the `sign-macos.sh` script locally unfortunately (I am out of code-signing certificates).
I just downloaded the last build and it crashes on my M1, because the libomp library is of the wrong architecture, this should combine the 2 architectures.

Combine arm64 and x86_64 libomp libraries

---

.github/workflows/cd.yml

Allow the workflow to be cancelled without running all remaining jobs.
On invocation of the workflow, cancel concurrent runs of older commits
automatically.
Replace unmaintained release action with recommended alternative.
After much testing, I found that the problem of releases
being created as draft releases can be traced to a
consistency issue/race condition on GitHub's side.
Prevent this by inserting a generous delay between deleting and
re-creating the edge release.

CI: Support cancelling, update actions & prevent draft releases

---

.github/workflows/cd.yml

The if condition was nonsensical and did not serve any
practical purpose; removing it allows the succeeding jobs
to run in any case without additional code.
Test for release event: https://github.com/ppd/solvespace/actions/runs/760219571
@phkahler We could re-create the release on this commit, or I could upload the assets manually and build the snaps locally. What do you prefer?

CI: Never skip cancel_previous_runs

---

src/platform/guigtk.cpp

Turns out the libsigc++ ones are false positives.

Add comment about asan warnings.

---

src/sketch.h
src/style.cpp

Fix a bug with the lookup of stipple pattern for default styles when the config settings are not yet available (install/upgrade/first run). This caused hidden lines to display as continuous rather than dashed.
This fixes #1027

Fix lookup of stipple pattern before config is available

---

src/constraint.cpp
src/drawconstraint.cpp

If a single point is selected when a "Constrain | Comment" (`;`) is added
then the comment is associated with the point and its position becomes
relative to the point. In this way the comment will move with the point.
If nothing is selected or more than a single point is selected then
the behaviour is as before and the comment is "floating".
Closes #1032
Alternative to https://github.com/solvespace/solvespace/pull/1034

Allow comments to be associated with point entities

---

src/importidf.cpp

Recent performance improvements make this reasonable to do, at least for simple circuit boards.

Show IDF keepout regions as construction entities.

---

src/group.cpp
src/sketch.h

I improved "Sketch in New Workplane" by adding two way of construction:
- point and normal
- point and face
I also added description in error popup:
I tried to be as less invasive as possible, and also tried to respect the coding style.
I have tested this code on Windows only.

Improve "Sketch in New Workplane" by adding two way of construction

---

CHANGELOG.md
developer_docs/IdLists_Entities_and_Remap.txt
developer_docs/Solver_Transforms.txt
src/clipboard.cpp
src/graphicswin.cpp
src/importidf.cpp
src/platform/guiwin.cpp
src/solvespace.cpp
src/srf/boolean.cpp
src/srf/curve.cpp
src/srf/triangulate.cpp
src/textscreens.cpp
src/textwin.cpp

Found via `codespell -q 3 -S ./res/locales,./extlib -L asign,ba,hsi,mata,tothe`

Fix various typos

---

src/graphicswin.cpp
src/group.cpp
src/ui.h

I prefer not to have showFaces set and it really bugs me that it is reset to true every time a non-drawing group is activated.
Assuming that most people want the current behaviour (show faces for non-drawings, hide for drawings) I've added 2 booleans, `showFacesDrawing` and `showFacesNonDrawing`, and clicking the show faces button updates whichever of those is appropriate for the current group type, so that showFaces is preserved independently between drawing and non-drawing groups.
The current behaviour will be preserved if you never touch the show faces button (because of the `showFacesNonDrawing = true` in `Init()`), but if you eg untick it when a non-drawing group is active, showFaces will stay disabled whenever a non-drawing group is activated (and vice versa).

Don't reset showFaces every time a group is activated

---

CMakeLists.txt

As per [cmake docs](https://cmake.org/cmake/help/v3.21/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html#variable:CMAKE_OSX_DEPLOYMENT_TARGET) this is how you configure `-mmacosx-version-min` in cmake land.
To my surprise this is all that was needed to get a binary compiled on 11.5.1 to launch on 10.12.6, which is as far back as I can test. 10.12.6 is supported on macs at least as far back as mid 2012.
Fixes #1086.
It did cause some build warnings from libomp:
ld: warning: dylib (/usr/local/lib/libomp.dylib) was built for newer macOS version (11.0) than being linked (10.12)
But again to my surprise this didn't seem to actually cause any problems (although different/future libomp versions may behave differently). In my very limited testing this change doesn't appear to have any noticeable impact …

Set OSX minimum supported version

---

src/confscreen.cpp
src/graphicswin.cpp
src/mouse.cpp
src/solvespace.cpp
src/solvespace.h
src/style.cpp
src/textscreens.cpp
src/ui.h
src/view.cpp

So that eg 30 inches is shown as `2' 6"`.
The rationale for this additional display mode is that I found myself transcribing a blueprint in feet and inches and while entering eg `2*12+6` for "2 feet 6 inches" was easy enough, not being able to see the dimensions in the constraints in the same format as the original made it difficult to go back and verify that everything had been entered correctly.
When editing, the text field still shows the value in inches, eg `30.00` in this example. In other words `Unit::FEET_INCHES` behaves mostly the same as `Unit::INCHES`. I did debate having the editable value match the display value, but that would require modifying `LexNumber()` and `StringToMm()` to understand the `xx' yy"` syntax and it felt like that might be a bit too invasive a change for …

Add option for displaying dimensions in feet and inches

---

src/confscreen.cpp
src/drawconstraint.cpp
src/drawentity.cpp
src/generate.cpp
src/graphicswin.cpp
src/group.cpp
src/sketch.h
src/solvespace.cpp
src/solvespace.h
src/ui.h

This PR adds an option to workplane sketches to draw all the entities in the sketch "exploded" normal to the workplane. The reason for doing this is that it makes it much easier to select lines and points which entirely overlap with other lines/points. I've found that when drawing a sketch from scratch in SolveSpace, I can usually use the "requests in group" list to find what I just added, but when importing complex DXFs created by other tools, that have all kinds of weird unexpected lines and constraints, it can be very difficult to figure out what constraints violations the import has created.
For example, here's a really basic sketch with a construction line hidden under the top line of the rect:
Here's the same sketch rotated (obviously, this doesn't help identify the construction …

Add an exploded view to sketches

---

src/textscreens.cpp
src/textwin.cpp

Throwing this one out there to see what people think.
I often lose track of which bits of a model I've temporarily hidden via the "suppress this group's solid model" tickbox. I could really do with a way to see what's suppressed and what's not in the main text window. So I made a simple patch to show suppressed groups in gray rather than the usual link blue:

Show suppressed groups in gray in the text window

---

src/group.cpp
src/importmesh.cpp
src/sketch.h
src/textscreens.cpp

Following on from comments by @Symbian9 https://github.com/solvespace/solvespace/pull/1095#issuecomment-903062126 I thought I'd try adding a `∆` indicator on groups that have 'force to triangle mesh' ticked, since that's also something that sometimes you need to scan down the entire group list to find (in my case, usually when trying different things to fix a NURBS issue).
I didn't go the whole way to adding identifiers for different group types, as @ruevs mentioned there's a point where you're making things less clear rather than more, if your group names are all prefixed with a string of punctuation. I did like the idea of using a `∆` character to indicate `forceToMesh` is set though, and I added it as a suffix in parentheses outside of the link colouration instead, to make it clearer …

Add a "∆" suffix to groups which have "force to triangle mesh" ticked.

---

src/platform/guimac.mm

Which are either not applicable for SolveSpace (the tabs ones) or are
already handled in the platform-independent code (the fullscreen item).
@vespakoen would you mind looking over this? I assume support for tabbed windows is unlikely to be needed any time soon :-)
(given `SS` and `SK` are globals thus preventing you ever having multiple sketches loaded in a single process, I actually started thinking about how to support opening multiple windows in the same process, and quickly gave up...)

mac: Remove spurious view menu items

---

.github/workflows/cd.yml
README.md

The snaps use git describe to determine
their grade (stable/devel). Fetch the tags to
make this possible.
Point users to the official release in the stable channel in README.md.

snap: Fetch tags for snap builds in CI & mention stable channel in README

---

.github/workflows/cd.yml
README.md

Re-creating the edge release for every push
to master creates many superfluous release notifications.
Stop creating those releases and provide users with direct
links to the workflow artifacts instead via the
nightly.link GitHub app (https://github.com/apps/nightly-link).
Fixes #1103

CI: Replace edge releases with links to artifacts

---

src/graphicswin.cpp
src/toolbar.cpp

If the main window is not high enough allow the default 32 pixel padding
between the menu bar and the toolbar to shrink down to zero.
This allows the main window height to be a minimum of 688 pixels (on
Windows 10) so it is possible to capture 720P video tutorials.
Fixes #1130

GUI: Flexible vertical space above the toolbar

---

src/file.cpp

This issue was mentioned on the forum. Linked STL groups don't have a NURBS shell, so they need to be forced to triangle mesh. The original STL code forced the previous group by mistake, and the fix for that didn't quite work. This seems to fix it.

fix STL linking issue. Model was disappearing after the link group.

---

src/platform/guimac.mm

To handle the Magic Mouse, whose single-finger touch gestures should be interpreted as scrollwheel events rather than pan gestures.
fixes #1106
@vespakoen does this look ok to you? Having to track the current number of active touches as an independent bit of state is slightly messy, but it does seem to do the trick without breaking actual trackpad support. Providing someone doesn't try zooming with a Magic Mouse single-finger gesture at the same time as panning with two fingers on a trackpad, I suppose...

mac: Don't interpret single-touch scroll events as pan gestures

---

src/resource.cpp

When SolveSpace tries to display an Unicode code point (e.g. U+EA00 ) that does not exist in the embedded vector font (unifont.hex.gz) it hangs in an endless loop in `const BitmapFont::Glyph &BitmapFont::GetGlyph(char32_t codepoint)`.
The reason is that the binary search through the text file unifont-8.0.01.hex that does the "lazy loading" of glyphs does not end.
Here is a short excerpt from the file:
```
D7FE:00007FFE63866DF66DEE6DDE63DE7FFE7FFE61866FBE638E6FBE6F867FFE0000
D7FF:00007FFE63866DF66DEE6DDE63DE7FFE7FFE61866FBE638E6FBE6FBE7FFE0000
F900:0080108810881FF8100800007FFE00000FF008100FF00810042002447FFE0000
F901:00047FFE008010841FFE10841FFC10841FFC10840880050003000CC0703E0000
```
When searching for `0xEA00` after some iterations of the while loop …

Fix hang when trying to display characters missing from the embedded font

---

cmake/MacOSXBundleInfo.plist.in
pkg/snap/snap/snapcraft.yaml
res/win32/versioninfo.rc.in
src/CMakeLists.txt
src/config.h.in

In 006539b, solvespace_MAJOR_VERSION etc. were removed.
However, these variables were still referenced in some places.
Solution: Use PROJECT_VERSION instead.
006539b removed the call to link_directories for gtkmm, jsonc & fontconfig.
This leads to linking errors if those libraries are in "non-standard"
paths.
Fix this by introducing a target specific target_link_directories call.
Fixes #1173
Moving to core20 was long overdue anyway, and
the recent CMake changes necessitated some fixes.
Also switch to LZO compression for (way) better cold start
performance.
I left the CMake commits separate for easier review. I/we can squash them before merging.

CMake Fixes + Snap port to core20

---

pkg/snap/snap/snapcraft.yaml

It got dropped in 34efb6de77 by mistake.

snap: add g++ as build package

---

src/resource.cpp

Load 16bit PNG images correctly by re-scaling to 8bit

---

src/textwin.cpp

When the text window/property browser is closed while and edit box
is active its window remained open. This is incorrect and probably
causes a hang on Linux described in #1168. So hide the edit control
when closing.
Probably Fixes #1168

Hide edit boxes before closing the property browser.

---

src/solvespace.h
src/system.cpp

in #1159 we used a sparse matrix to hold expr pointers, when all we do with them is evaluate them into a sparse matrix of doubles. This stores them as a vector of triplets instead of the matrix, which makes it easy to evaluate to a vector of triplets with double data, from which we can set the sparse matrix efficiently. This actually shaved about 0.1s off of the test suite execution time (in relwithdebinfo) vs just #1159 on its own, so I think we probably want this one if we want that one.

No sparse expr

---

src/describescreen.cpp

This makes all points and appropriate vectors/normals shown in the Property Browser window explorable/selectable and closes #165.
This is a clean implementation that follows the style of the UI code for
the text window. Previous unmerged attempts from the above issue are:
https://github.com/Evil-Spirit/solvespace-master/commit/eb3db32059bc5b3a4264aba7524ea1cd3e39b8f3
https://github.com/wpwrak/solvespace/commit/782a5bbbe61c0a1e5326d55218de33e6a7682f26
https://github.com/wpwrak/solvespace/commit/a77cedbfd8dedd147fb59ebf9af936f4259ff31b
https://github.com/wpwrak/solvespace/commit/41e55b3d79f7d2df61fb9db0b494ff09a37d6add

Make points/vectors/normals shown in the Property Browser into active links

---

src/importmesh.cpp

This is more of a WIP.  It no longer locks up if you link a text formated STL file, but the dialog we get is not helpful.

Check for text STL when linking

---

.github/workflows/cd.yml

Snapd stopped working in Docker containers in commit
https://github.com/snapcore/snapd/commit/c6011693a816f7f8a5b0c7858ddce91c6ef1a352
Therefore, we cannot use the current build action,
which relies on Docker to implement cross-compilation.
Switching to the upstream build action avoids the problem at the cost
of losing the arm64 builds on amd64 hardware.
Those need to be reintroduced by some other mechanism,
e.g. via Launchpad, in the future.
Fixes #1229

CI: Use upstream action to build snap & drop arm64 snap

---

src/solvespace.cpp
src/solvespace.h

Fixes #920, #1143
Explanation from @robnee on Feb 7, 2021 in pull request #927
Solvespace uses two timers (generateAllTimer and showTWTimer) to defer tasks until the event loop processing finishes. This helps coalesce multiple calls into one. You can call scheduleGenerateAll multiple times while processing UI messages but only trigger one GenerateAll. scheduleGenerateAll and scheduleShowTW do their scheuduling by setting timers with durations of zero. These timers fire (at least on Linux and Windows) some time after all other events in the message queue have been processed. This works fine when scheduling either one of these tasks. However, there is no guarantee in what order the timers will fire (at least on Windows) regardless of which order the scheduling calls are made. It's pretty …

Make scheduled/deferred task order deterministic

---

src/describescreen.cpp

Since 7e08b02de1d91580f691dbe5eed08e2ccfd24eed comments can be attached to
points.
Now when such a comment is selected the point (entity) it is associated to
will be shown in the text window together with it's coordinates and the
distance (offset) from the point to the comment.
Most of this was already prepared by Whitequark here
https://github.com/solvespace/solvespace/commit/afa9e2890ef7ab46242d5f67f7bab1e58e80c2ba
I just had to to remove the original 12 year old code by jwesthues that
showed "SELECTED: comment text" for comments.
(https://github.com/solvespace/solvespace/commit/6750995ef0b79c9ee83244fe34797f24e8aed582)
Fixes #1072

Show details for comments associated with points

---

CMakeLists.txt

Link 32 bit SolveSpace for Windows with /LARGEADDRESSAWARE which allows
it to access up to 3GB of RAM on a properly configured 32 bit Windows and
up to 4GB on 64 bit.
See: https://msdn.microsoft.com/en-us/library/aa366778
https://docs.microsoft.com/en-us/cpp/build/reference/largeaddressaware-handle-large-addresses
https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#characteristics
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc786709
https://docs.microsoft.com/en-us/windows/win32/memory/4-gigabyte-tuning
Fixes: #1261

Win32: Allow 32 bit SolveSpace to access up to 4GB of RAM.

---

.github/workflows/source-tarball.yml

As suggested by someone helping with the flathub packaging: https://github.com/rpavlik/flathub/pull/1#discussion_r911211382  Too late for 3.1 but having it in place for the next release will make life easier for packagers (including flatpak)

Stamp source tarballs with the commit hash

---

pkg/snap/snap/snapcraft.yaml

- Migration according to https://forum.snapcraft.io/t/micro-howto-migrate-from-core20-to-core22/30188
- Also declare all snaps stable
What's left?

snap: Port to core22

---

res/locales/fr_FR.po

"Step" has plenty of meanings, and the wrong one was used here: "espacement" roughly means "spacing", which is very confusing for the "Step dimension" feature, and weird for "Step translation"/"Step rotation".
Instead, I chose to translate it as:
* "Pas-à-pas" for the former, which is a noun for lack of a verb that fully captures the meaning, which literally translates to "step-by-step". "Pas-à-pas" is also the common translation of "Step debugging" in programming.
* "Répétiter par" for the latter, which is a verb (+ adverb) which literally translates to "Repeat by" and is the most natural way to phrase this.
As a side-effect, I made a key binding consistent with English.

Fix French translations of "Step"

---

res/locales/fr_FR.po

"Rotation Importation 90°" was the only noun group in this part of the menu.
This replaces it with an infinitive group like the rest of the menu, which is also easier to understand.

Fix inconsistent French translation of "Rotate Imported"

---

CMakeLists.txt
cmake/FindCairo.cmake

The pkg detection of Cairo (at least on FreeBSD) doesn't work well.
Cairo is found, but forgot to add a `-L%%PREFIX%%/lib` where `%%PREFIX%%` is usually `/usr/local` on FreeBSD.
```shell
[ 51% 130/254] : && /usr/bin/c++ -fPIC -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -ffile-prefix-map=/wrkdirs/usr/ports/cad/solvespace/work/solvespace-3.1=. -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wfloat-conversion -Werror=switch -O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -fstack-protector-strong -shared -Wl,-soname,libslvs.so.1 -o bin/libslvs.so.3.1 src/CMakeFiles/slvs.dir/util.cpp.o src/CMakeFiles/slvs.dir/entity.cpp.o src/CMakeFiles/slvs.dir/expr.cpp.o src/CMakeFiles/slvs.dir/constraint.cpp.o src/CMakeFiles/slvs.dir/constrainteq.cpp.o …
```

CMake: Add FindCairo.cmake to fix build on FreeBSD

---

src/file.cpp

This appears to fix #1297. Using this on top of #1296, I was able to fix up my `.slvs` file with desktop portal paths to STLs to use proper relative paths instead.
I still see extra dialog boxes about how the original, desktop portal path files could not be read, but the re-linking works and my file seems fine afterward.

Allow all linkable files as missing files to fix #1297

---

res/locales/fr_FR.po

Source: https://www.wordreference.com/enfr/constraint

Fix "Constraintes" typo in French locale

---

src/graphicswin.cpp

Prior to this commit, the "Nearest Isometric" GUI command searched all 24 possible isometric views.  When using turntable navigation, this could result in the z-axis no longer being oriented vertically.  This commit restricts the views being searched while in turntable navigation mode to those that follow this restriction.

[Graphics][Bugfix] Make "Nearest Isometric" follow turntable navigation

---

src/platform/gui.h
src/platform/guigtk.cpp
src/platform/guihtml.cpp
src/platform/guimac.mm
src/platform/guiwin.cpp

The fuction GetDevicePixelRatio now returns a `double` instead of an `int`. This should allow the scaling of the GUI on devices where the pixel ratio is non integer to work properly. For example a monitor on Windows where the DPI is not a multiple of 96. It may help with the Web Emscripten port on tablets and phones as well.
In addition on Windows the mouse wheel delta calculation is fixed.

Platform: Fix GUI scaling on devices with non-integer pixel ratio

---

src/constraint.cpp

Didn't test it thoroughly. Also there is a question about undo - should multiple constraints be trated as individual items for undo?

Sync multiconstraint with current state

---

src/constraint.cpp
src/describescreen.cpp
src/draw.cpp
src/groupmesh.cpp
src/ui.h

This allows the user to select 3 faces vs the old limit of 2.  I would like to allow constraining a point to more than one face at a time, and 3 would be the maximum. This is a prerequisite to that.
The remaining problem is that the 3rd selected face is not shown as selected. The selection code indicates that the limit of 2 was for rendering performance reasons, which may or may not be a problem today. I'm not sure where the relevant rendering code is to show the selected faces. Help would be appreciated but this is a low priority. Might be a good way for someone to dig into more obscure parts of the code.

Add ability to select 3 faces

---

src/group.cpp

Treat group as mesh only if a linked file has a mesh and no shell.

---

src/confscreen.cpp
src/mouse.cpp
src/solvespace.cpp
src/solvespace.h
src/ui.h

issue #325 requests an alternative to middle-button mouse navigation/rotation.  What I think the user is asking for is an option to manipulate the camera instead of model when rotating, i.e. reversing up/down and left/right directions.  This PR implements that feature (independent of turntable navigation) as a config option called "camera mouse navigation" (name could use some work).  It drives me a little bit crazy but I think some are used to this and would welcome this option.

Add config option for "camera" rotation navigation

---

src/solvespace.cpp

This fixes #1320, but not #1239. The root cause for the avalanche of messages is due to how the refresh timer system calls GenerateAll. When GenerateAll is called by Refresh, if a Message occurs, that Message will block GenerateAll. It _doesn't_ block subsequent calls from the timer to Refresh (presumably from a separate thread). Because the "scheduledGenerateAll" flag is not cleared until after the generation is unblocked, each following refresh triggers another call to GenerateAll. By reversing the flag clear and call, it breaks the cycle. I don't think this matters for scheduledShowTW, but I updated it as well. 
I am going to look into what might be causing #1239 next, but I think it is due to something unrelated.
P.S. I am still getting my bearings on the codebase, so please nitpick …

Fix MessageBox Avalanches due to Message blocking

---

src/constraint.cpp

This was a regression Introduced in 3d3d5c7.
Fixes #1345

Fix a crash when constraining a line segment symmetric

---

.github/workflows/test.yml

The outdated runner problem seems to also exist in the tests, mentioned in the pull request #1383. Like the previous pr, this updates the problematic runners.

Update test.yml with ubuntu-latest and macos-latest

---

.github/ISSUE_TEMPLATE.md

macOS SolveSpace has the Help menu but it lacks the About menu item in it and instead the way to find the SolveSpace version is to go to SolveSpace > About SolveSpace. This PR updates the issue template to show that.
I have also replaced the `...` with an ellipsis (`…`) as it IMO looks better (can revert this if it doesn't match the menu item on Windows/Linux) and updated the example version to the current SolveSpace version.

Update the issue template to show where to look for SolveSpace version on macOS

---

src/graphicswin.cpp

Limit view changes to 800ms transition time as suggested in a review.

Speed up view change animations

---

src/platform/platform.cpp

MinGW-w64 MinGW-Builds 13.1.0 on the other hand does not need this.

Win32: Fix for compiling with MinGW.org GCC-6.3.0-1

---

src/group.cpp
src/mouse.cpp

To avoid unnecessary/annoying copies of images added in 2d sketches if they are marked "construction" they will not be copied when creating solids.
Fixes: #1418

Do not include construction images in extrude/lathe/revolve/helix

---

.github/scripts/install-macos.sh

Big Sur -> Ventura
I'm trying to get solvespace to build on aarch64 MacOS Ventura. The CI Build for MacOS is failing because homebrew no longer has the big_sur tags downloaded in the macos-install.sh script

[WIP] Fix MacOS Build

---

cmake/Platform/Emscripten.cmake

Web version crashes when you try to make a constraint. After debugging, addressed the issue with this PR. Emscripten does some optimization stuff and ends up dropping certain functions, including the alloacte function called in solvespace's C++ Unwrap method.
To reproduce/test bug:
- Open the web version
- Create a rectangle
- Create a length constraint on one the rectangle edges

[web] Add allocate function as emscripten dep

---

pkg/snap/snap/snapcraft.yaml

This will fix https://github.com/solvespace/solvespace/issues/1067 by setting GTK_USE_PORTAL=0 in the Snap package. This will use a file chooser from the point of view of the application to open and save files, instead of using the "desktop portal" where the chooser runs outside the snap and the file is exposed dynamically into the snap at an automatically generated path.
This will allow files used in assemblies to be seen by SolveSpace as being at their real paths, so the references to them will be saved as proper relative-path references based on where the files actually are, instead of as references to where the portal has exposed them.
The downside is that without the portal you can't point the application at files that *aren't* exposed to the Snap.

Bypass desktop portal in Snap

---

src/clipboard.cpp

fixes issue #1372
As mentioned in issue, this bug is caused by using absolute value of `scale` when calculating constraints in paste transformed. 
I removed `fabs()` exactly for pt_line_distance case.
Tested for different geometry and it works ok now.
I'm quite new to open-source contributions on GitHub, so excuse me if i missed something or did something wrong.

fix pt-line distance constraint bug on paste transformed

---

src/ttf.cpp

The comment "@todo identify fonts by their name and not filename" was was added in https://github.com/solvespace/solvespace/commit/784f3e55481e99885f1c64b94b7cee49ea670158 but seems to have been already implemented at that time since TTF fonts are sorted and filtered by their font name instead of file name.

NFC: Remove ToDo comment that appears to be done

---

src/platform/guiwin.cpp

On Windows when going full screen by pressing CTRL-F11 the Property Browser window remained hidden behind the main window until one ALT-Tab-ed to it or to another application and back.
This commit fixes it.
The fix is not mine. It comes from this Chinese fork: https://gitee.com/zhongzhiSys/SolveSpace
where they mostly took 2.3 and started selectively merging fixes from 3.x with their own commit messages. There are however original fixes like this one interspersed with the merges. I have not finished going through everything.

Win32: the Property Browser remains visible when going full screen (CTRL-F11)

---

src/clipboard.cpp
src/constraint.cpp
src/sketch.h

Implements #937
Test cases:
[ArcsLinesSplinesTangentTests.zip](https://github.com/user-attachments/files/17648175/ArcsLinesSplinesTangentTests.zip)
https://github.com/solvespace/solvespace/pull/833#issuecomment-742082682
https://github.com/solvespace/solvespace/pull/833#issuecomment-744528586
Cross references:
https://github.com/solvespace/solvespace/pull/833
96958f466395148ee7f0a252222a2a27e7345c22
https://github.com/solvespace/solvespace/issues/937
https://github.com/solvespace/solvespace/pull/948
8c101d5f281ba670a3af2663302fe3dc7fb15283
https://github.com/solvespace/solvespace/issues/951
https://github.com/solvespace/solvespace/issues/1492

Allow tangent on arcs/lines/splines without coincident endpoints.

---

src/graphicswin.cpp

With this pressing ESC while drawing a bezier curve finishes it instead of deleting it. This reverts the behaviour introduced in b34d9a2f1161362f049a4e380cc81acd3262bedd (p.r. #1386). ESC still deletes the last segment of line segments and cancels arcs and circles.
This makes it easier to draw non closed curves - otherwise the only way to finish them was with a right-click.

GUI: Allow ESC to finish drawing bezier curves instead of deleting them.

---

src/confscreen.cpp
src/graphicswin.cpp
src/solvespace.cpp
src/solvespace.h
src/ui.h

This is a minor adjustment to add a configuration setting for the animation speed, including disabling them completely.
The animation time equation has been slightly changed to accommodate this, but it should behave mostly the same as before. With the default setting of 800ms you should get approximately the same as before.

Make the animation speed configurable

---

src/platform/guihtml.cpp

Change `ContextLostCallback` and `ContextRestoredCallback` to return `bool` because that is what the current Emscripten API wants. The web version now compiles.
Reference:
https://emscripten.org/docs/api_reference/html5.h.html#id92

Web: Fix compilation with current Emscripten

---

src/file.cpp

If the file name is written in capital letter solvespace crashes on my system.
Some applications do export with "STL" instead of "stl".
This would solve this.

add handling for STL file instead of only stl file

---

src/clipboard.cpp

In dedc6d48f475790006f672e6ffd1b2470a6fdd60 I missed a break statement. GCC caught it with a warning.
It was not causing an observable bug, but it is better to fix it.

Add a forgotten `break` statement. Should be and NFC.

---

src/platform/guimac.mm

Fixes #1494, by only saving the last navigated directory when one actually exists.
I'd originally written the following as a reply to that issue, but decided to fix the bug myself instead.
---
I repro'd using 3.1~70bde63c — it happened when saving to the default directory the first few times. After I navigated to a different directory on a subsequent save, the crash no longer occurred; I'd say it's because `Dialog_Sketch_Folder` gets set and so `nsPanel.directoryURL` gets a value when thawed.
To reproduce:
1. Ensure SolveSpace is closed.
2. Run:
```shell
plutil -remove Dialog_Sketch_Folder ~/Library/Preferences/com.solvespace.plist
```
3. Open SolveSpace.
4. Choose File → Save.
5. Click Save in the opened dialog. SolveSpace crashes.
You can repeat steps 3 to 5 after this. To stop the …

mac: don't crash on file ops without changing dir

---

.github/workflows/python.yml
pyproject.toml
src/lib.pyx

For some reason the Cython bindings contain invalid type annotations, even though the accompanying `.pyi` file has them correctly. This causes warnings to be emitted  during the Python library build, so I changed them to match.

Fix issues with type annotations in the Cython bindings

---

.github/workflows/python.yml

This is required for building wheels for Python 3.12 and 3.13 (fixes the CI failures after merging #1530 ).

ci: update the `pypa/cibuildwheel` action to v2.22.0

---

CMakeLists.txt
src/CMakeLists.txt

The CMake `SYSTEM` modifier of `target_include_directories()` must come before the visibility specification. However, it was accidentally in the wrong order, so it was simply adding a directory named `SYSTEM` to the target's include paths.
Fix it to correctly request the include paths to be treated as system include paths.

build: fix CMake system include directives

---

.gitmodules
CMakeLists.txt

The existing version (2.7.1) is using an ancient zlib version, which fails to build with modern Xcode tools on macOS.
Fixes #1539

Update the vendored FreeType version to 2.13.3

---

CMakeLists.txt
cmake/Platform/Emscripten.cmake
cmake/Toolchain-emscripten.cmake
res/CMakeLists.txt
src/CMakeLists.txt
src/platform/guihtml.cpp

The Emscripten port is currently broken with the latest Emscripten tools due to the way the toolchain is defined, so this PR gets rid of the bespoke toolchain files in favour of the official Emscripten one (it's not needed if an emsdk environment is active).
In addition to the build issues, some of the hacks that were made in the port broke with the latest toolchain, causing runtime issues and crashing. This PR fixes just enough issues to make the port usable again so that it's at least able to run and have a functional interface. Additional work is still needed to bring it to feature parity with the native ports.

emscripten: fix build issues and make the interface functional

---

CMakeLists.txt
res/CMakeLists.txt

Commit 3ac128d9723c45ec9c353cd159f16e524964153a (merged in #1564) updated the Emscripten toolchain configuration to the official one, and accidentally broke the build due to a `zlib` issue that was missed (the issue is briefly described in a comment that I added for this change, but see [my comment in the other PR](https://github.com/solvespace/solvespace/pull/1564#issuecomment-2803091398) for a longer explanation).
In the next `zlib` version this can be properly fixed, but until it's released we can work around it by unsetting `UNIX` for Emscripten right before including `zlib` and resetting it back again.

Add a workaround for building zlib in Emscripten

---

.github/scripts/build-wasmlib.sh
pyproject.toml
src/CMakeLists.txt
src/slvs/CMakeLists.txt

Similar to #1558, the CI Python build has been failing because the CMake dependency in `pyproject.toml` was not pinned to a specific version and it was pulling version 4.0.0 with the compatibility issue.
Additionally, I inadvertently broke the CI build in #1561 by introducing more granular targets without adjusting the installation of those targets accordingly. This PR fixes it by introducing CMake components and using them in the Python build, and properly specifying the WASM target in the build script.

ci: fix the broken Python and WASM library builds

---

js/slvs.d.ts
src/generate.cpp
src/slvs/lib.cpp
src/solvespace.h
src/system.cpp

It wasn't set inside `System::Solve()`, and it's not useful anyway when rank testing is fully or partially suppressed.
OTOH, in `System::SolveRank()` it is useful, and although it wasn't set, it was actually checked in `Constraint::TryConstrain()` (through the call to `SolveSpaceUI::TestRankForGroup()`), so fix it by letting `System::TestRank()` set it if provided.

Remove the unused and unset rank parameter from `System::Solve()` and fix it in `System::SolveRank()`

---

cmake/GetGitCommitHash.cmake
include/slvs.h
src/textwin.cpp

This PR includes minor build-related fixes for warnings that were encountered when compiling with GCC 14.2, as well as the following enhancements:
* Avoid exporting functions from `slvs` if built as a static library on Windows, as this needlessly exposes them when linked into a DLL.
* Allow getting the Git hash automatically when built as a submodule. This useful enhancement was taken from https://github.com/realthunder/solvespace

Minor build-related fixes and enhancements

---

CONTRIBUTING.md

The guide was incorrectly using I/O "threads" instead of I/O streams, and the part about platform-specific functionality was referring to old files that don't exist anymore.

docs: minor correction to the contribution guide and update references

---

CMakeLists.txt
README.md

This includes updating the ANGLE dependency to the latest commit in our fork which fixes a build issue with GCC.
Additionally, a minor change to the build configuration was needed for building under 64-bit MinGW, which doesn't support `--large-address-aware`.
With those in place, the documentation for building under MinGW is updated with working instructions and a recommendation to use MSYS2 for easier installation of the required tools.
@phkahler had reservations regarding the change to ANGLE in https://github.com/solvespace/angle/pull/2, which this PR relies on, so I'm just opening this PR in order to put the fix out there in case this is acceptable, but please feel free to close it if not.
Fixes #1570.

build: fix MinGW build failures and update documentation

---

.gitmodules

For the past few weeks there have been multiple times where CI failed because it encountered 502 errors while cloning the FreeType repository from its current URL.
The official FreeType repository is now hosted in the freedesktop GitLab instance, but in order to reduce the load on their servers, and to also hopefully reduce the chance that CI fails again due to unavailability, I chose to use the official GitHub mirror instead.
Related: https://github.com/solvespace/solvespace/pull/1575#issuecomment-2845257449, https://github.com/solvespace/solvespace/pull/1563#issuecomment-2787364549

freetype: update the submodule URL to the official GitHub mirror

---

src/dsc.h
src/expr.cpp
src/expr.h
src/generate.cpp
src/sketch.h
src/slvs/lib.cpp
src/solvespace.h
src/system.cpp

This PR cleans up and optimises various parts of the solver, especially around `SolveBySubstitution()` and `WriteJacobian()`. The latter can result in noticeable speedups on some models (see initial numbers in my comment [here](https://github.com/solvespace/solvespace/pull/1563#issuecomment-2807422537)).
-----
~While trying to look into #1247 I was having trouble reproducing the issue, and the model was failing in weird ways (such as multiple constraints not satisfied, causing horizontal and vertical lines to become diagonal).~
~After staring hard at the code for a long time, I finally traced the issue down to commit 708a08f04b910337965859249b87684696369219 (merged in #1159) which made changes in order to speed up solving by substitution. However, the changes inadvertently  caused …

Solver: clean up and optimise `SolveBySubstitution()` and `WriteJacobian()`

---

CMakeLists.txt

Commit 2a455285a3cc12b42197a5ca573ae5347c95d84d (merged in #1566) added an ugly workaround for building zlib with Emscripten. This commit provides a cleaner way, which doesn't require messing around with built-in variables that define the environment.

build: clean up the workaround for building zlib in Emscripten

---

src/CMakeLists.txt

With CMake >= 3.22, the "-Xlinker /MANIFEST:EMBED" flag is provided even when no manifest files are added, and since we add our own manifest file through a resource file, this fails with a duplicate resource error.
Unfortunately there's no easy way to avoid it, other than special casing for CMake >= 3.22 to add the manifest as a source for non-MINGW WIN32, and exclude it from the resources, but otherwise add it to the resource file.
However, this solution requires conditionally reaching into `res/` from the `src/` directory build, which is really bad, so for now hack out the offending part from `CMAKE_CXX_LINK_EXECUTABLE`, since we actually don't want it.

build: fix link error when building on Windows with Clang (not clang-cl)

---

src/generate.cpp

Calling `Message()` can cause processing of a scheduled dirty regeneration while the message box is still shown. Since the deleted stats are only zeroed after the message box is dismissed, this can cause the message box to be shown multiple times.
Fix it by changing the code to reset the deleted stats and use a saved copy for showing the message box.
Fixes #1239.

generate: avoid message box avalanche on Windows during regeneration

---

src/generate.cpp
src/graphicswin.cpp
src/solvespace.h

Commit 86f20cc7e5061d14323fdc0d814980922425e152 (merged in #428) was marked NFC, even though it didn't just convert loops to ranged-for, but also introduced a functional change in the request pruning logic to prune entities instead.
This doesn't make much sense, since the requests will stay, and their entities will simply be regenerated, leading to an infinite recursion and resulting in a crash with stack overflow. I'm not sure how it slipped past code review, but this was the cause of #628 and is the reason for the additional workplane deletion code that whitequark added in 586b0477d2be31b2ac24c351f5eeeb90f86a7c2b, so this PR also reverts that code as well.

generate: fix `PruneRequests()` to actually prune requests

---

src/constrainteq.cpp
src/expr.cpp
src/file.cpp
src/generate.cpp
src/group.cpp
src/request.cpp
src/sketch.h
src/slvs/lib.cpp
src/solvespace.h

For some reason, even though the `ParamList` and `EntityList` aliases exist, parts of the code still spell the full type names (`IdList<Param, hParam>` and `IdList<Entity, hEntity>`, respectively). This makes the code verbose, less readable, and inconsistent. This PR changes it so that they use the aliases for better readability and consistency.

Minor cleanup: use the ParamList and EntityList type aliases

---

CHANGELOG.md
src/exportstep.cpp
src/solvespace.h

After bb6cc1a0..d1b52cd6 in the exported STEP files "half" of the
`ORIENTED_EDGE`s were in the wrong direction. This caused some tools (e.g.
Kisters 3DViewStation) to render them incorrectly (this is understandable).
Fixed by flipping edges when required, keeping an `orientedEdgeAliases`,
list and reusing them.

STEP export: fix broken export - `ORIENTED_EDGE`s are properly oriented.

---

cmake/c_flag_overrides.cmake

For some reason the [/MT options in the `CMAKE_C_FLAGS_RELEASE_INIT`](https://github.com/solvespace/solvespace/blob/0df1ba74089b41316630270c1a44070672ab1966/cmake/c_flag_overrides.cmake#L4) etc. CMake targets stopped working at some point and SolveSpace became linked to the DLL versions of the C/C++ runtime (MSVCP140.DLL, VCRUNTIME140.DLL).
We do not like this. Therefore:
Use the proper "modern" CMake incantation to make SolveSpace static again ;-)
https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html
The OpenMP build still depends on VCOMP140.DLL but this seems unavoidable.
https://stackoverflow.com/questions/37037733/statically-link-with-microsoft-crt-and-openmp
https://github.com/godotengine/godot/issues/14935

Win32: Make SolveSpace grea...static again

---

CMakeLists.txt

Something changed in the way compiler flags are passed by CMake to the compiler, which caused the OpenMP flags to be passed as a single flag and resulting in a build failure.
Use CMake's `SHELL:` syntax to tell CMake to pass these as separate flags, but without reordering them or performing deduplication.

build: fix building with OpenMP on macOS

---

include/slvs.h
src/slvs/jslib.cpp
src/slvs/lib.cpp
src/slvs/lib.pyx

`WHERE_DRAGGED` locks points in place, whereas `System::dragged` merely asks the solver to move them as little as possible, so using both doesn't make much sense (see my comment [here](https://github.com/solvespace/solvespace/pull/1561#issuecomment-2787581610), where I made a similarly wrong assumption).
Instead, add a new API to mark points as dragged without constraining them with `WHERE_DRAGGED`, and expose it in the bindings as well.
NOTE: the changes in this PR conflict with #1563, so I'll rebase the PR that ends up in conflict after one of them is merged.

slvs: don't mark `WHERE_DRAGGED` constraints as dragged
