.appveyor/irc-notify.py, res/shaders/edge.frag, src/srf/ratpoly.cpp, src/ui.h
Found via `codespell -q 3 --skip="./res/locales,./extlib"`
=> Misc. typos

src/graphicswin.cpp, src/toolbar.cpp
Fixes two uninitialized memory errors in the toolbar.
=> Uninitialized memory errors

src/platform/guiwin.cpp
By the way @whitequark - that was an impressive marathon on May 23-24 :-)
=> Fix building with OPENGL=1

src/textwin.cpp
Higher contrast colours in the text window for readability. Much lighter blue and somewhat lighter yellow.
=> Brighter blue and yellow in text window for higher contrast/readability.

src/export.cpp
Opted for an explicit span container for clarity but that can be easily replaced with explicit iterator-`for`s if you're not a fan
=> Export transparency correctly in VRML

src/importdxf.cpp, src/lib.cpp, src/platform/gui.h, src/platform/guigtk.cpp, src/platform/guimac.mm, src/platform/guinone.cpp, src/platform/guiwin.cpp, src/polygon.h, src/polyline.cpp, src/render/gl3shader.cpp, src/render/gl3shader.h, src/render/render.cpp, src/render/render.h, src/resource.cpp, src/resource.h
Found and suggested by clang-tidy.
May help performance by reducing copies,
depending on frequency of call, etc.
I have to go in and fix the Windows build.
=> WIP Make some arguments const/const references, where possible

developer_docs/Solver_Transforms.txt
Adds a developer_documentation folder and a new description of how to create new ways to copy entities in the solver. Quality is up for debate, but it may be better than nothing ;-)
=> Developer notes for creating new entity transformations in the solver.

src/mouse.cpp
This changes all the lambdas to have explicit captures, since the use of implicit captures has led to some memory errors, especially segfaults in the right-click menu.
I'm not 100% sure that the code is correct anyway - it really needs auditing to ensure all referenced values are still valid when the menu item is clicked (e.g. can you change stuff with keyboard shortcuts while the context menu is visible?), but it should at least be *more* correct!
=> Fix more segfaults in mouse.cpp lambdas

src/srf/ratpoly.cpp, src/srf/surface.h
This is cleaner and smaller, but I was not able to measure a performance impact.
=> Bernstein polynomials with no branching.

src/polygon.cpp, src/polygon.h
Clean up and slight work reduction.
=> NFC: Assemble polygon

src/constraint.cpp
to edit "Length Ratio" and "Length Difference"
=> Expand "edit newly added dimensions"

CHANGELOG.md, src/bsp.cpp, src/groupmesh.cpp, src/mesh.cpp, src/polygon.h, src/sketch.h, src/srf/boolean.cpp, src/srf/surface.h, src/textscreens.cpp
The NURBS operation is properly implemented.
ToDo: The mesh operation in SMesh::MakeFromIntersectionOf
is still done as C=A-(A-B).
Implements: https://github.com/solvespace/solvespace/issues/35
=> NURBS: Add intersection boolean operation.

src/group.cpp
Bugs were introduced in PR #582.
=> Fix use-after-free in Lathe, Revolve, and Helix. Issue #611.

README.md
Now consistent with the invocation halfway up
=> Fix extlib/q3d{o,} typo in README

src/srf/raycast.cpp
Cleanup, missed this one when eliminating Random().
=> Don't init srand(0) because rand isn't used any more.

src/srf/triangulate.cpp
The commits for each are separate. For 639 we resolve all test cases.
=> Fix issues 296 and 639

res/locales/de_DE.po, res/locales/en_US.po, res/locales/fr_FR.po, res/locales/ru_RU.po, res/locales/uk_UA.po, res/messages.pot
for all languages. See PR #705
my russian is not good enough to fix the remaining ru and uk strings.
german and french are now complete.
=> translate_solvespace updates

src/CMakeLists.txt, src/file.cpp, src/group.cpp, src/importidf.cpp, src/platform/gui.cpp, src/platform/gui.h, src/solvespace.h
Can read PCB outlines and cutouts, as well as Pin and Mounting holes. Import should be considered deprecated as the sketch is no very useful.
Not ready for merging but I want it out there to get feedback from the community. I hope to add Routing Keepouts as construction lines, and do some cleanups. Components may come later if there is interest.
=> WIP: IDF file Linking & Import.

src/importdxf.cpp
Extrusion direction (normal) of arcs and circles were not taken into
account when importing.
- Add method for calculating a quaternion from extrusion direction
according to DXF arbitrary axis algorithm
- Add required workplanes for arcs not on XY origin plane
- Adjust addDimRadial and addDimDiametric to include normal when
creating associated circle request
=> Allow DXF import of 3D arcs and circles

src/platform/guiwin.cpp
=> Fix issue 684 as whitequark suggested via WM_KEYDOWN->WMCHAR change.

src/platform/guimac.mm
=> Fix for https://github.com/solvespace/solvespace/issues/248

.travis.yml, .travis/build-macos.sh, .travis/install-macos.sh, .travis/sign-macos.sh, CMakeLists.txt
=> Add macOS travis config, fix issue in CMakeLists.txt causing macOS build to break

.travis/build-macos.sh, .travis/sign-macos.sh, src/CMakeLists.txt
Those were already in my old PR, somehow forgot the bring them into the last one and basically did the work twice now 😂
=> macOS CI fixes

.gitignore, .travis.yml, .travis/build-debian.sh, .travis/build-macos.sh, .travis/build-windows.sh, .travis/install-macos.sh, .travis/sign-macos.sh, CMakeLists.txt, src/drawentity.cpp, src/mouse.cpp, src/solvespace.h
Removing deploy step from macOS CI `test` stage.
Will also add the `if: tag IS present` condition if the first build succeeds.
=> Remove deploy step for macOS CI

.travis/build-macos.sh
- Turns on the `-DENABLE_LTO` flag during deploy
- Turns off the `-DENABLE_OPENMP` flag during test
- Wraps some arguments in quotes
=> Travis: optimize macOS deploy build

src/solvespace.cpp
It's 2020 ;-)
https://github.com/solvespace/solvespace/issues/772
=> Update the year in the About dialog

README.md
Do we want something like this? I'm proposing it to start a discussion. 
Maybe something like a licence badge too:
=> README: Add Travis & Snap Store badges

src/draw.cpp
=> Use zOrder for selections within the same group

src/draw.cpp, src/render/render.cpp, src/render/render.h, src/ui.h
Seems to work for points and lines. May want to test a bit more.
=> Add z distance checking to entity picking. Fixes issue 521

res/locales/de_DE.po, res/locales/en_US.po, res/locales/fr_FR.po, res/locales/ru_RU.po, res/locales/uk_UA.po, res/locales/zh_CN.po, res/messages.pot
for the solvespace.cpp changes.
Run make -C src translate_solvespace for updated line numbers for the rest.
=> Translations: update de_DE

src/platform/guigtk.cpp
Just filled in the TODO on GTK version.
=> Use good default filenames on Linux/GTK

src/clipboard.cpp, src/constraint.cpp
This reverts commit 14e837a45f599b9b2a8a28d8628f96490b593c24.
Fixes a regression described here:
https://github.com/solvespace/solvespace/issues/875
=> Revert "Clean up paste transformed and constrain operations a bit."

res/locales/de_DE.po, res/locales/en_US.po, res/locales/fr_FR.po, res/locales/ru_RU.po, res/locales/uk_UA.po, res/locales/zh_CN.po, res/messages.pot
See #890
make -C src translate_solvespace to update all line numbers
=> Translations: update de_DE for 3.0

res/locales/de_DE.po, res/locales/en_US.po, res/locales/fr_FR.po, res/locales/ru_RU.po, res/locales/uk_UA.po, res/locales/zh_CN.po, res/messages.pot, src/graphicswin.cpp
Discussion here:  https://github.com/solvespace/solvespace/issues/890
=> Change "Dim Solid for Sketch Groups" to "Darken Inactive Solids"

res/locales/de_DE.po
See #890 and its changed menu item
2 more missing
=> Improved de_DE

src/platform/entrycli.cpp
=> Add version command to solvespace-cli

src/mouse.cpp
I believe there is a glitch in the way the Property Browser display is updated when dragging.  Currently, when one starts tp drag an entity such as a point it's details will briefly appear in the Property Browser.  This is due to the fact that initially the mouse-down event selects the entity being hovered.  Once the mouse begins to move the state transitions from selection to dragging.  This causes the Property Browser to be cleared (reverts to group display) during the duration of the drag which does not show anything useful.  Alternatively, when dragging an entity that was _already_ selected, the entity remains in the selected state and the Property Browser continues to show the dragged entity's details.  I feel the latter behavior is more informative.
This PR tweaks the selection to …
=> Update property browser display live when dragging

src/CMakeLists.txt, src/file.cpp, src/importmesh.cpp, src/platform/gui.cpp, src/solvespace.h
Some edge vertexes fail to add a point entity. Not sure why. Otherwise this is working OK.
=> Add STL Linking. Experimental.

src/group.cpp, src/textscreens.cpp, src/ui.h
The idea here is to use the group valB as the pitch parameter. I believe the math and constraint equation are correct.
There is a problem in the text window - it crashes when setting the pitch parameter.
Also not sure about using the parameter itself as a flag for enabling the constraint, but that's how it is now.
=> Add optional helix pitch constraint.  WIP

res/CMakeLists.txt, res/locales.txt, res/locales/de_DE.po, res/locales/en_US.po, res/locales/es_AR.po, res/locales/fr_FR.po, res/locales/ru_RU.po, res/locales/tr_TR.po, res/locales/uk_UA.po, res/locales/zh_CN.po, res/messages.pot
This enables the new es-AR translation and also updates the .pot file.
=> update pot file and locales.txt and CMakeLists.txt for spanish.

src/importidf.cpp, src/platform/gui.h, src/platform/platform.h, src/resource.h, src/solvespace.h
The namespace thing should make editors and IDEs like the code more, reducing maintenance burden. The other commit fixes a bug identified by a warning on my machine.
=> Normalize namespaces and fix uninitialized

CMakeLists.txt, cmake/FindSpaceWare.cmake, src/CMakeLists.txt, src/expr.cpp, src/expr.h, src/generate.cpp, src/sketch.h, src/solvespace.h, src/system.cpp, src/textscreens.cpp
This is just the solver changes from #721, skipping the final commits that add Eigen, and fixed so that every commit successfully builds. I do not fully understand the changes, I just can rebase them sensibly. @Evil-Spirit is the real author here.
I'll put the Eigen stuff in a separate PR.
This does run.
With sanitizers enabled, looks like no new  leaks thru here.
=> Solver changes without eigen

.github/scripts/install-macos.sh, .github/scripts/install-ubuntu.sh, .gitmodules, CMakeLists.txt, README.md, pkg/snap/snap/snapcraft.yaml, src/CMakeLists.txt, src/expr.cpp, src/expr.h, src/solvespace.h, src/system.cpp
This is the Eigen-related stuff from #721, but put over my Eigen work excluding my work in the system.cpp file (so most but not all of #432 ).  Builds on #1158 and #1155 
I also split out the "too many unknowns" removal and put it at the end, in case we want to keep a now-artificial limit.
No new leaks.
=> Evilspirit eigen over ryan buildsys

res/win32/versioninfo.rc.in, src/solvespace.cpp
Update the year in the About dialog and the Windows version info.
=> Happy New Year 2022

src/system.cpp
Turns out this introduced a small performance regression, at least with OpenMP enabled.
Using my largest on-hand solvespace file, with the name "threaded-tube-mess.slvs" :D, this one commit slowed the benchmark down from <0.600s to 0.637 (Release build, MSVC2022, OpenMP), running each test a few times to make sure all caches are warm, etc.
This reverts commit 985e4fb67a96a1d9f444a764594bcaa1373281a8.
=> Revert "OpenMP-enable the evaluation of a jacobian."

.gitignore
Visual Studio 2022 creates these files that we want to ignore.
=> Add some gitignore stuff

res/locales/tr_TR.po
I translated the new entries in the Turkish language file (tr_TR.po) and rearranged the old file.
=> I Translated Turkish Language File

.github/workflows/source-tarball.yml
Closes #1028 
See https://github.com/ppd/solvespace/releases/tag/v8.5 for an exemplary release
=> CI: Create tarballs with submodules included for releases

src/describescreen.cpp
=> UI: Display the circumference of a circle in the property browser

src/platform/guimac.mm
This reverts commit 91db627a81a1438ca4e02f0b27c6f17ceac1051c.
=> Revert "mac: Don't interpret single-touch scroll events as pan gestures"

res/locales/de_DE.po
Remaining strings translated and some minor fixes.
=> German translation completed

src/describescreen.cpp
Add some face and point types to describe screen.
=> Add some face and point types to describe screen

src/platform/guimac.mm
This is the second attempt to distinguish trackpad scrolling that when used
should yield panning from Magic Mouse scrolling that should control zoom.
Since trackpad will begin with a touch prior to the scroll event, but Magic
Mouse not, we can use it to make sure we trigger panning only on a trackpad.
Previous "mac: Don't interpret single-touch scroll events as pan gestures"
that was flawed was reverted which ultimately lead to being unable to zoom using
Magic Mouse.
This fixes again #1107 and is also related to #1218
=> mac: Distinguish trackpad from Magic Mouse scroll

res/locales/ru_RU.po
Mostly removing the unnecessary title case — that's not how Russian typography works :)
=> Update Russian translation

src/srf/boolean.cpp, src/srf/raycast.cpp, src/srf/surface.h, src/srf/surfinter.cpp
and one small code reduction/optimization.
=> Rename shell enums so they don't conflict with bsp enums

src/importidf.cpp
Avoid to add duplicate drilled holes to the entity list checking if what's read from the emn file exists there. It's quite slow. Solves #1375.
=> skip duplicate drilled holes

src/graphicswin.cpp
Fix for https://github.com/solvespace/solvespace/issues/1244
=> Fix language bug

src/draw.cpp
=> Make segment selection more precise

src/graphicswin.cpp
Becasue I Shift-tab didn't work...
I don't know if we want this, but it fits with TAB hiding the text window.
=> CTRL-TAB un/hides the toolbar

src/draw.cpp, src/mesh.cpp, src/platform/guihtml.cpp, src/platform/html/filemanagerui.js, src/platform/html/solvespaceui.js, src/srf/raycast.cpp, src/view.cpp
Apparently I had this laying around.
=> Codespell fixes

src/platform/guigtk.cpp
An alternative to https://github.com/solvespace/solvespace/pull/1464
=> GTK: Handle smooth scrolling according to the documentation

src/draw.cpp, src/export.cpp, src/file.cpp, src/graphicswin.cpp, src/render/render2d.cpp, src/srf/boolean.cpp
Could help with compiler optimizations and thus performance.
=> Use `const auto &` in a few for loops that were not doing it.

res/locales/fr_FR.po
cc @ruevs (https://github.com/solvespace/solvespace/issues/1515)
=> Fix inconsistent punctuation in French translation and translate new strings.

res/locales/ja_JP.po
Update translation of ja_JP. https://github.com/solvespace/solvespace/issues/1515
Added translations for new messages and updated for existing translated messages.
=> Update ja_JP translation.

src/render/rendergl1.cpp
This needlessly uses the global temporary arena, when the lifetime can be managed by replacing `GLU_TESS_COMBINE` with `GLU_TESS_COMBINE_DATA` instead.
While the use of the global temporary arena is mostly harmless, having it around needlessly prevents restricting the arena's scope to the sketch in a possible future where the global sketch is removed. Additionally, it means that calls to `FreeAllTemporary()` must synchronise with the renderer, which is a needless restriction on the users of the arena given the fact that none of the other renderers use it.
=> render: remove a call to `AllocTemporary()` from the OpenGL 1 renderer

src/constrainteq.cpp, src/system.cpp, src/textscreens.cpp
I added parameters to text window for debugging, but I remembered @ruevs already has a PR up for that. So I will bump these changes off
=> Fix parameters "failed to solve" bug when adding a relation constraint

src/slvs/lib.cpp
The current initial satisfaction code expects a constraint to only generate a single equation in order to be initially satisfiable. However, some constraints generate more than a single equation, and this hits an assertion.
SolveSpace itself only initially satisfies a small subset of constraints, so there is no point in trying to satisfy all types.
Fixes #1379
=> slvs: don't try to initially satisfy unsupported constraints

src/slvs/lib.cpp
Unlike the system solving API, the sketch solving API keeps its state between solve calls unless `Slvs_ClearSketch()` is called.
This can lead to constraint params being orphaned and regenerated when the sketch isn't cleared between solve calls. While not a correctness issue, it does waste memory and throws away existing numeric guesses. Fix it by identifying this case and regenerating only if we actually need to.
=> slvs: avoid orphaning params in the sketch with the sketch solving API
